CREATE TABLE plants (
    plant_id INT PRIMARY KEY,
    Genus VARCHAR(255),
    Species VARCHAR(255),
    Cultivar VARCHAR(255),
    Common_Name VARCHAR(255),
    Latin_Name VARCHAR(255),
    Family VARCHAR(255),
    Order_ VARCHAR(255),
    Class_ VARCHAR(255),
    Bloom_Time VARCHAR(255),
    Sun_Requirements VARCHAR(255),
    Soil_Requirements VARCHAR(255),
    Hardiness_Zone INT,
    Height INT,
    Spread INT,
    Growth_Rate VARCHAR(255),
    Flower_Color VARCHAR(255),
    Foliage_Color VARCHAR(255),
    Fragrance ENUM('yes', 'no'),
    Uses TEXT,
    Growing_Guide TEXT,
    Water_Requirements VARCHAR(255),
    Soil_Drainage VARCHAR(255),
    pH_Requirements VARCHAR(255),
    Temperature_Requirements VARCHAR(255),
    Pests_and_Diseases TEXT,
    Companion_Plants TEXT,
    Image_URL VARCHAR(255),
    UK_Legal_Protection VARCHAR(255),
    Wildlife_Attraction VARCHAR(255),
    Pollinator_Friendly ENUM('yes', 'no', 'unknown'),
    Mature_Height_and_Spread VARCHAR(255),
    Time_to_Maturity VARCHAR(255),
    Drought_Tolerance ENUM('yes', 'no', 'moderate'),
    Soil_Amendment_Recommendations TEXT,
    Additional_Notes TEXT,
    Plant_Type VARCHAR(50) NOT NULL
);

INSERT INTO plants VALUES (
    1,
    'Rosa',
    'gallica',
    'Versicolor',
    'Rosa Mundi',
    'Rosa gallica Versicolor',
    'Rosaceae',
    'Rosales',
    'Magnoliopsida',
    'Summer',
    'Full Sun',
    'Well-drained soil',
    4,
    3,
    2,
    'Medium',
    'Pink and white striped',
    'Green',
    'yes',
    'Ornamental, Cut Flowers',
    'Plant in a sunny location with well-drained soil. Prune in late winter or early spring.',
    'Regular',
    'Well-drained',
    'Neutral to slightly acidic',
    'Moderate',
    'Aphids, Black Spot',
    'Lavender, Catmint',
    'image_url_rose.jpg',
    NULL,
    'Attracts butterflies',
    'yes',
    '3 feet x 2 feet',
    '2-5 years',
    'Moderate',
    'Compost in spring',
    'This historic rose is known for its distinctive striped flowers.',
    'Rose'
);

INSERT INTO plants VALUES (
    2,
    'Myosotis',
    'sylvatica',
    NULL,
    'Forget-Me-Not',
    'Myosotis sylvatica',
    'Boraginaceae',
    'Boraginales',
    'Magnoliopsida',
    'Spring to early summer',
    'Partial shade to full sun',
    'Moist, well-drained soil',
    3,
    6,
    18,
    'Moderate',
    'Shades of blue, pink, or white',
    'Green',
    'Mild',
    'Ground cover, borders, containers',
    'Plant in early spring in well-draining soil. Keep soil consistently moist.',
    'Regular watering',
    'Well-drained',
    'Slightly acidic to neutral',
    'Cool to mild temperatures',
    NULL,
    'Columbine, Bleeding Heart',
    'image_url_forget_me_not.jpg',
    NULL,
    NULL,
    NULL,
    NULL,
    '2 - 3 months',
    'Low',
    'Forget-Me-Nots are often associated with love and remembrance, making them perfect for gift-giving.',
    'Forget-Me-Not'
);

INSERT INTO plants VALUES (
    3,
    'Fuchsia',
    'hybrida',
    'Gartenmeister Bonstedt',
    'Gartenmeister Bonstedt Fuchsia',
    'Fuchsia hybrida Gartenmeister Bonstedt',
    'Onagraceae',
    NULL,
    NULL,
    'Summer to fall',
    'Partial shade to full sun',
    'Moist, well-drained soil',
    9,
    3,
    2,
    'Fast',
    'Bright orange-red',
    'Green',
    'Mild',
    'Container plant, Hanging baskets',
    'Plant in a location with filtered sunlight. Keep soil consistently moist. Prune to shape in late winter or early spring.',
    'Regular watering',
    'Well-drained',
    'Slightly acidic to neutral',
    'Moderate',
    'Aphids, Spider mites',
    'Begonia, Lobelia',
    'image_url_fuchsia.jpg',
    NULL,
    'Attracts hummingbirds',
    'yes',
    '2 feet x 2 feet',
    '1-2 years',
    'Moderate',
    'Balanced liquid fertilizer every 2-4 weeks during the growing season.',
    'Gartenmeister Bonstedt Fuchsia'
);

INSERT INTO plants VALUES (
    4,
    'Rosmarinus',
    'officinalis',
    NULL,
    'Rosemary',
    'Rosmarinus officinalis',
    'Lamiaceae',
    'Lamiales',
    'Magnoliopsida',
    'Spring to summer',
    'Full Sun',
    'Well-drained, sandy soil',
    8,
    3,
    4,
    'Medium',
    'Blue, purple',
    'Green',
    'Fragrant',
    'Culinary, Medicinal, Ornamental',
    'Plant in a sunny location with well-drained soil. Water sparingly and allow the soil to dry out between waterings.',
    'Low',
    'Well-drained',
    'Slightly acidic to neutral',
    'Warm temperatures',
    'Aphids, Snails',
    'Lavender, Sage',
    'image_url_rosemary.jpg',
    NULL,
    'Attracts bees',
    'yes',
    '3 feet x 4 feet',
    '2-3 years',
    'High',
    'Organic compost in spring. Prune regularly to maintain shape.',
    'Rosemary is a versatile herb used in cooking, aromatherapy, and traditional medicine.'
);

INSERT INTO plants VALUES (
    5,
    'Allium',
    'sativum',
    NULL,
    'Garlic',
    'Allium sativum',
    'Amaryllidaceae',
    'Asparagales',
    'Liliopsida',
    'Late fall to early spring',
    'Full Sun',
    'Well-drained, loamy soil',
    3,
    2,
    1,
    'Medium',
    'White',
    'Green',
    'Mild',
    'Culinary, Medicinal',
    'Plant individual cloves in the fall, pointed end up, in well-drained soil. Harvest when the tops yellow and fall over.',
    'Moderate',
    'Well-drained',
    'Slightly acidic to neutral',
    'Cool temperatures',
    'Aphids, Nematodes',
    'Lettuce, Beets',
    'image_url_garlic.jpg',
    NULL,
    'Repels pests in the garden',
    'yes',
    '1 foot x 1 foot',
    '8-9 months',
    'High',
    'Organic fertilizer in spring. Mulch around plants to conserve moisture.',
    'Garlic is not only a staple in the kitchen but also known for its health benefits and pest-repelling properties.'
);

INSERT INTO plants VALUES (
    6,
    'Thymus',
    'vulgaris',
    NULL,
    'Thyme',
    'Thymus vulgaris',
    'Lamiaceae',
    'Lamiales',
    'Magnoliopsida',
    'Spring to summer',
    'Full Sun',
    'Well-drained, sandy soil',
    5,
    1,
    1,
    'Slow',
    'White, pink, lavender',
    'Green',
    'Fragrant',
    'Culinary, Medicinal, Ground Cover',
    'Plant in a sunny location with well-drained soil. Allow the soil to dry out between waterings.',
    'Low',
    'Well-drained',
    'Slightly acidic to neutral',
    'Warm temperatures',
    'Spider Mites, Root Rot',
    'Lavender, Rosemary',
    'image_url_thyme.jpg',
    NULL,
    'Attracts bees and butterflies',
    'yes',
    '6 inches x 12 inches',
    '2-3 years',
    'Moderate',
    'Compost in spring. Prune regularly to maintain shape.',
    'Thyme is a versatile herb used in cooking, teas, and as a fragrant ground cover in the garden.'
);

INSERT INTO plants VALUES (
  7,
  'Origanum',
  'vulgare',
  'Aureum',
  'Golden Oregano',
  'Origanum vulgare Aureum',
  'Lamiaceae',
  'Lamiales',
  'Magnoliopsida',
  'Late spring to early summer',
  'Full Sun',
  'Well-drained, sandy soil',
  5,
  8,
  12,
  'Medium',
  'Pink to purple',
  'Golden yellow',
  'Fragrant',
  'Culinary, Medicinal, Ground Cover',
  'Plant in a sunny location with well-drained soil. Allow the soil to dry out between waterings.',
  'Low',
  'Well-drained',
  'Slightly acidic to neutral',
  'Warm temperatures',
  'Spider Mites, Root Rot',
  'Basil, Rosemary',
  'image_url_oregano.jpg',
  NULL,
  'Attracts bees and butterflies',
  'yes',
  '8 inches x 12 inches',
  '2-3 years',
  'Moderate',
  'Compost in spring. Prune regularly to maintain shape.',
  'Golden Oregano is a culinary delight with its golden foliage and aromatic leaves.'
);


INSERT INTO plants VALUES (
    8,
    'Lavandula',
    'angustifolia',
    NULL,
    'Lavender',
    'Lavandula angustifolia',
    'Lamiaceae',
    'Lamiales',
    'Magnoliopsida',
    'Late spring to early summer',
    'Full Sun',
    'Well-drained, sandy soil',
    5,
    2,
    2,
    'Slow',
    'Lavender',
    'Gray-green',
    'Fragrant',
    'Culinary, Medicinal, Ornamental',
    'Plant in a sunny location with well-drained soil. Prune after flowering to maintain shape and encourage new growth.',
    'Low',
    'Well-drained',
    'Slightly alkaline to neutral',
    'Warm temperatures',
    'Aphids, Spider Mites',
    'Rosemary, Sage',
    'image_url_lavender.jpg',
    NULL,
    'Attracts bees and butterflies',
    'yes',
    '12 inches x 18 inches',
    '2-3 years',
    'Low',
    'Organic mulch around the base to conserve moisture.',
    'Lavender is known for its calming fragrance and various uses in cooking and aromatherapy.'
);

INSERT INTO plants VALUES (
    9,
    'Ocimum',
    'basilicum',
    'Genovese',
    'Genovese Basil',
    'Ocimum basilicum Genovese',
    'Lamiaceae',
    'Lamiales',
    'Magnoliopsida',
    'Late spring to early fall',
    'Full Sun',
    'Well-drained, fertile soil',
    9,
    1,
    1,
    'Fast',
    'White',
    'Green',
    'Fragrant',
    'Culinary, Medicinal, Ornamental',
    'Plant in a sunny location with well-drained soil. Pinch off flower buds to encourage leaf production.',
    'Regular watering',
    'Well-drained',
    'Slightly acidic to neutral',
    'Warm temperatures',
    'Aphids, Whiteflies',
    'Tomatoes, Peppers',
    'image_url_basil.jpg',
    NULL,
    'Attracts bees',
    'yes',
    '12 inches x 18 inches',
    '2-3 months',
    'Moderate',
    'Organic fertilizer during the growing season.',
    'Genovese Basil is a classic culinary herb, perfect for pesto and various dishes.'
);

INSERT INTO plants VALUES (
    10,
    'Matricaria',
    'recutita',
    NULL,
    'German Chamomile',
    'Matricaria recutita',
    'Asteraceae',
    'Asterales',
    'Magnoliopsida',
    'Late spring to early summer',
    'Full Sun',
    'Well-drained, sandy soil',
    4,
    1,
    1,
    'Moderate',
    'White',
    'Green',
    'Fragrant',
    'Medicinal, Ornamental',
    'Sow seeds directly in the garden in early spring. Harvest flowers when fully open for tea or medicinal use.',
    'Regular watering',
    'Well-drained',
    'Slightly acidic to neutral',
    'Cool temperatures',
    'Aphids, Thrips',
    'Cabbage, Onions',
    'image_url_chamomile.jpg',
    NULL,
    'Attracts beneficial insects',
    'yes',
    '8 inches x 12 inches',
    '2-3 months',
    'Moderate',
    'Avoid over-fertilization to maintain the aromatic qualities of the flowers.',
    'German Chamomile is known for its soothing properties and is commonly used in herbal teas and natural remedies.'
);

INSERT INTO plants VALUES (
    11,
    'Petroselinum',
    'crispum',
    'Moss Curled',
    'Moss Curled Parsley',
    'Petroselinum crispum Moss Curled',
    'Apiaceae',
    'Apiales',
    'Magnoliopsida',
    'Spring to fall',
    'Partial shade to full sun',
    'Well-drained, moist soil',
    5,
    1,
    1,
    'Slow',
    'Green',
    'Green',
    'Mild',
    'Culinary, Medicinal, Ornamental',
    'Sow seeds directly in the garden. Harvest outer leaves for continuous growth.',
    'Regular watering',
    'Well-drained',
    'Slightly acidic to neutral',
    'Cool to warm temperatures',
    'Aphids, Slugs',
    'Tomatoes, Roses',
    'image_url_parsley.jpg',
    NULL,
    'Attracts butterflies',
    'yes',
    '8 inches x 12 inches',
    '2-3 months',
    'Moderate',
    'Companion plant for tomatoes and roses.',
    'Moss Curled Parsley is a versatile herb used in various culinary dishes and as a garnish.'
);

INSERT INTO plants VALUES (
    12,
    'Salvia',
    'officinalis',
    'Common',
    'Common Sage',
    'Salvia officinalis Common',
    'Lamiaceae',
    'Lamiales',
    'Magnoliopsida',
    'Late spring to early summer',
    'Full Sun',
    'Well-drained, sandy soil',
    5,
    2,
    2,
    'Medium',
    'Blue',
    'Green',
    'Fragrant',
    'Culinary, Medicinal, Ornamental',
    'Plant in a sunny location with well-drained soil. Prune regularly to maintain shape.',
    'Low',
    'Well-drained',
    'Slightly alkaline to neutral',
    'Warm temperatures',
    'Aphids, Slugs',
    'Rosemary, Lavender',
    'image_url_sage.jpg',
    NULL,
    'Attracts bees and butterflies',
    'yes',
    '18 inches x 24 inches',
    '2-3 years',
    'Low',
    'Avoid over-watering to prevent root rot.',
    'Common Sage is a classic herb known for its culinary and medicinal uses.'
);

INSERT INTO plants VALUES (
    13,
    'Allium',
    'schoenoprasum',
    NULL,
    'Chives',
    'Allium schoenoprasum',
    'Amaryllidaceae',
    'Asparagales',
    'Liliopsida',
    'Late spring to early summer',
    'Full Sun to partial shade',
    'Well-drained, fertile soil',
    4,
    1,
    1,
    'Fast',
    'Purple',
    'Green',
    'Mild',
    'Culinary, Medicinal, Ornamental',
    'Plant in well-drained soil. Harvest leaves for culinary use, leaving some for the plant to regenerate.',
    'Regular watering',
    'Well-drained',
    'Slightly acidic to neutral',
    'Cool to warm temperatures',
    'Aphids, Thrips',
    'Tomatoes, Carrots',
    'image_url_chives.jpg',
    NULL,
    'Attracts beneficial insects',
    'yes',
    '12 inches x 12 inches',
    '2-3 months',
    'Moderate',
    'Divide clumps every 3-4 years for healthy growth.',
    'Chives add a mild onion flavor to dishes and are a delightful addition to herb gardens.'
);

INSERT INTO plants VALUES (
    14,
    'Mentha',
    'spicata',
    'Spearmint',
    'Spearmint',
    'Mentha spicata Spearmint',
    'Lamiaceae',
    'Lamiales',
    'Magnoliopsida',
    'Late spring to early summer',
    'Partial shade to full sun',
    'Well-drained, moist soil',
    4,
    1,
    1,
    'Fast',
    'Purple',
    'Green',
    'Fragrant',
    'Culinary, Medicinal, Ornamental',
    'Plant in well-drained soil. Mint can be invasive, consider planting in containers.',
    'Regular watering',
    'Well-drained',
    'Slightly acidic to neutral',
    'Cool to warm temperatures',
    'Aphids, Spider Mites',
    'Basil, Rosemary',
    'image_url_mint.jpg',
    NULL,
    'Attracts bees and butterflies',
    'yes',
    '12 inches x 18 inches',
    '2-3 months',
    'High',
    'Prune regularly to control growth and encourage bushiness.',
    'Spearmint is a versatile herb used in beverages, desserts, and medicinal applications.'
);

INSERT INTO plants VALUES (
    15,
    'Coriandrum',
    'sativum',
    'Cilantro',
    'Cilantro',
    'Coriandrum sativum Cilantro',
    'Apiaceae',
    'Apiales',
    'Magnoliopsida',
    'Late spring to early summer',
    'Partial shade to full sun',
    'Well-drained, moist soil',
    8,
    1,
    1,
    'Fast',
    'White',
    'Green',
    'Mild',
    'Culinary, Medicinal, Ornamental',
    'Sow seeds directly in the garden. Harvest leaves for culinary use, and seeds for spice.',
    'Regular watering',
    'Well-drained',
    'Slightly acidic to neutral',
    'Cool to warm temperatures',
    'Aphids, Spider Mites',
    'Cilantro, Dill',
    'image_url_coriander.jpg',
    NULL,
    'Attracts beneficial insects',
    'yes',
    '12 inches x 12 inches',
    '2-3 months',
    'Moderate',
    'Plant successive crops for continuous harvest.',
    'Cilantro adds a fresh and citrusy flavor to various dishes.'
);

INSERT INTO plants VALUES (
    16,
    'Anethum',
    'graveolens',
    'Bouquet',
    'Dill',
    'Anethum graveolens Bouquet',
    'Apiaceae',
    'Apiales',
    'Magnoliopsida',
    'Late spring to early summer',
    'Full Sun',
    'Well-drained, fertile soil',
    6,
    3,
    1,
    'Fast',
    'Yellow',
    'Green',
    'Mild',
    'Culinary, Medicinal, Ornamental',
    'Sow seeds directly in the garden. Harvest leaves and seeds for culinary use.',
    'Regular watering',
    'Well-drained',
    'Neutral to slightly alkaline',
    'Cool temperatures',
    'Aphids, Spider Mites',
    'Coriander, Fennel',
    'image_url_dill.jpg',
    NULL,
    'Attracts beneficial insects',
    'yes',
    '12 inches x 12 inches',
    '2-3 months',
    'Moderate',
    'Harvest regularly to promote continuous growth.',
    'Dill is a flavorful herb commonly used in pickling and various culinary dishes.'
);

INSERT INTO plants VALUES (
    19,
    'Artemisia',
    'dracunculus',
    'French',
    'French Tarragon',
    'Artemisia dracunculus French',
    'Asteraceae',
    'Asterales',
    'Magnoliopsida',
    'Late spring to early summer',
    'Full Sun',
    'Well-drained, sandy soil',
    5,
    1,
    1,
    'Slow',
    'Yellow-green',
    'Green',
    'Mild',
    'Culinary, Medicinal, Ornamental',
    'Plant in well-drained soil. Harvest leaves for culinary use.',
    'Low watering needs',
    'Well-drained',
    'Slightly acidic to neutral',
    'Warm temperatures',
    'Aphids, Spider Mites',
    'Chives, Sage',
    'image_url_tarragon.jpg',
    NULL,
    'Attracts bees and butterflies',
    'yes',
    '18 inches x 18 inches',
    '2-3 years',
    'Low',
    'Prune regularly to encourage bushy growth.',
    'French Tarragon is prized for its aromatic leaves, essential in French cuisine.'
);

INSERT INTO plants VALUES (
    22,
    'Origanum',
    'majorana',
    'Sweet',
    'Sweet Marjoram',
    'Origanum majorana Sweet',
    'Lamiaceae',
    'Lamiales',
    'Magnoliopsida',
    'Late spring to early summer',
    'Full Sun',
    'Well-drained, fertile soil',
    5,
    1,
    1,
    'Medium',
    'White',
    'Green',
    'Mild',
    'Culinary, Medicinal, Ornamental',
    'Plant in well-drained soil. Harvest leaves for culinary use.',
    'Regular watering',
    'Well-drained',
    'Slightly acidic to neutral',
    'Warm temperatures',
    'Aphids, Spider Mites',
    'Basil, Thyme',
    'image_url_marjoram.jpg',
    NULL,
    'Attracts bees and butterflies',
    'yes',
    '12 inches x 12 inches',
    '2-3 years',
    'Low',
    'Sweet Marjoram has a mild, sweet flavor and is often used in cooking and herbal remedies.'
);
--FRUITS!
-- Example for Apple Tree
INSERT INTO plants VALUES (
    23,
    'Malus',
    'domestica',
    'Bramley',
    'Bramley Apple Tree',
    'Malus domestica Bramley',
    'Rosaceae',
    'Rosales',
    'Magnoliopsida',
    'Late spring',
    'Full Sun',
    'Well-drained, loamy soil',
    4,
    10,
    8,
    'Medium',
    'White',
    'Green',
    'Mild',
    'Edible, Ornamental',
    'Plant in well-drained soil. Prune in late winter to shape and encourage fruiting.',
    'Regular watering',
    'Well-drained',
    'Slightly acidic to neutral',
    'Cool to warm temperatures',
    'Aphids, Codling Moth',
    'Pear, Plum',
    'image_url_apple.jpg',
    NULL,
    'Attracts bees',
    'yes',
    '15 feet x 12 feet',
    '3-5 years',
    'Moderate',
    'Apply mulch to retain soil moisture.',
    'The Bramley Apple is a popular cooking apple known for its large size and tart flavor.'
);
-- Example for Strawberry Plant
INSERT INTO plants VALUES (
    24,
    'Fragaria',
    '× ananassa',
    'Elsanta',
    'Elsanta Strawberry Plant',
    'Fragaria × ananassa Elsanta',
    'Rosaceae',
    'Rosales',
    'Magnoliopsida',
    'Late spring to early summer',
    'Full Sun to partial shade',
    'Well-drained, slightly acidic soil',
    4,
    0,
    8,
    'Fast',
    'White',
    'Green',
    'Mild',
    'Edible, Ground cover',
    'Plant in well-drained soil. Provide support for runners and protect from birds.',
    'Regular watering',
    'Well-drained',
    'Slightly acidic',
    'Cool to mild temperatures',
    'Aphids, Slugs',
    'Lettuce, Spinach',
    'image_url_strawberry.jpg',
    NULL,
    'Attracts bees',
    'yes',
    '6 inches x 12 inches',
    '1-2 years',
    'Low',
    'Renew plants every 2-3 years for optimal yield.',
    'Elsanta Strawberries are a popular variety known for their large, sweet berries.'
);
-- Example for Raspberry Bush
INSERT INTO plants VALUES (
    25,
    'Rubus',
    'idaeus',
    'Autumn Bliss',
    'Autumn Bliss Raspberry Bush',
    'Rubus idaeus Autumn Bliss',
    'Rosaceae',
    'Rosales',
    'Magnoliopsida',
    'Late summer to early fall',
    'Full Sun to partial shade',
    'Well-drained, fertile soil',
    4,
    4,
    3,
    'Fast',
    'White',
    'Green',
    'Mild',
    'Edible, Ornamental',
    'Plant in well-drained soil. Prune after fruiting to encourage new growth.',
    'Regular watering',
    'Well-drained',
    'Slightly acidic to neutral',
    'Cool to mild temperatures',
    'Aphids, Japanese Beetle',
    'Blackberry, Blueberry',
    'image_url_raspberry.jpg',
    NULL,
    'Attracts bees',
    'yes',
    '4 feet x 3 feet',
    '2-3 years',
    'Moderate',
    'Provide support for canes as they grow.',
    'Autumn Bliss Raspberries are a popular variety with sweet and flavorful berries.'
);
-- Example for Pear Tree
INSERT INTO plants VALUES (
    26,
    'Pyrus',
    'communis',
    'Conference',
    'Conference Pear Tree',
    'Pyrus communis Conference',
    'Rosaceae',
    'Rosales',
    'Magnoliopsida',
    'Late summer to early fall',
    'Full Sun',
    'Well-drained, loamy soil',
    4,
    12,
    8,
    'Medium',
    'White',
    'Green',
    'Mild',
    'Edible, Ornamental',
    'Plant in well-drained soil. Prune in late winter to shape and encourage fruiting.',
    'Regular watering',
    'Well-drained',
    'Slightly acidic to neutral',
    'Cool to warm temperatures',
    'Aphids, Codling Moth',
    'Apple, Plum',
    'image_url_pear.jpg',
    NULL,
    'Attracts bees',
    'yes',
    '15 feet x 12 feet',
    '3-5 years',
    'Moderate',
    'Apply mulch to retain soil moisture.',
    'The Conference Pear is a popular variety known for its sweet and juicy fruit.'
);
