#!/usr/bin/env python3
"""feeds.py — regenerate feed.xml from the live catalogue + deterministic picks.

    python3 scripts/promo/feeds.py            # rewrite feed.xml
    python3 scripts/promo/feeds.py --check    # fail if it is out of date

The feed used to be hand-maintained and rotted: it advertised 1164 tools and
carried a "No tracking" line that contradicts the site's analytics. Now the
weekly refresh regenerates it: the last 7 daily picks, the week's track, and
two rotating evergreen funnel items (embed / licence / hire / sync). That
makes the feed a genuine discovery surface again — and it doubles as a free
newsletter backend: point any RSS-to-email service at it and subscribers get
the week's tools with zero ongoing effort.
"""
from __future__ import annotations

import argparse
import datetime
import os
import sys
from xml.sax.saxutils import escape

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from promo import catalogue, pick  # noqa: E402

SITE = catalogue.SITE
OUT = os.path.join(catalogue.ROOT, "feed.xml")
GENERATED = "<!-- generated by scripts/promo/feeds.py — do not hand-edit -->"

EVERGREENS = [
    ("Embed any tool on your site",
     f"{SITE}/embed.html",
     "Every tool embeds with one iframe — free with a credit line, "
     "white-label licences from £99/year."),
    ("White-label licences for all 1119 tools",
     f"{SITE}/license.html",
     "One tool £99/year, a whole category £299/year, everything £899/year. "
     "Your branding, maintained UK figures, zero third-party scripts."),
    ("Need a custom calculator or tool?",
     f"{SITE}/hire.html",
     "Calculator audits from £149, custom builds from £495, working demo "
     "before you pay the balance."),
    ("Music for your video, game or ad",
     f"{SITE}/sync.html",
     "Animated MrProphecy tracks, cleared in a single conversation. Creator "
     "licences from £50."),
]


def _rfc822(day: datetime.date) -> str:
    dt = datetime.datetime(day.year, day.month, day.day, 12, 0,
                           tzinfo=datetime.timezone.utc)
    return dt.strftime("%a, %d %b %Y %H:%M:%S +0000")


def _item(*, title: str, link: str, guid: str, pub: str, desc: str) -> str:
    return (
        "  <item>\n"
        f"    <title>{escape(title)}</title>\n"
        f"    <link>{escape(link)}</link>\n"
        f'    <guid isPermaLink="false">{escape(guid)}</guid>\n'
        f"    <pubDate>{pub}</pubDate>\n"
        f"    <description><![CDATA[{desc}]]></description>\n"
        "  </item>"
    )


def build(as_of: datetime.date) -> str:
    tools = catalogue.load_tools()
    count = len(tools)
    items: list[str] = []
    for back in range(6, -1, -1):
        day = as_of - datetime.timedelta(days=back)
        tool = pick.pick_tool(day, tools)
        title = catalogue.plain(tool.get("title") or tool["name"])
        desc = catalogue.short(tool.get("description") or "Free browser tool.", 300)
        url = catalogue.tool_url(tool["name"])
        items.append(_item(
            title=f"Tool of the day: {title}",
            link=url, guid=f"pick-{day.isoformat()}-{tool['name']}",
            pub=_rfc822(day),
            desc=f"{escape(desc)} Free in your browser, no sign-up. "
                 f"Category: {escape(tool.get('category') or 'General')}."))
    track = pick.pick_track(as_of)
    track = {**track, "url": catalogue.track_url(track["youtube_id"])}
    year, week, _ = as_of.isocalendar()
    items.append(_item(
        title=f"Track of the week: {catalogue.safe_text(track['title'])}",
        link=track["url"], guid=f"track-{year}-W{week:02d}-{track['youtube_id']}",
        pub=_rfc822(as_of),
        desc="An animated MrProphecy music video — free to watch. Sync "
             f"licences from £50: {SITE}/sync.html"))
    rot = (as_of - pick.EPOCH).days // 7
    for i in range(2):
        title, link, desc = EVERGREENS[(rot + i) % len(EVERGREENS)]
        items.append(_item(
            title=title.replace("1119", str(count)), link=link,
            guid=f"evergreen-{(rot + i) % len(EVERGREENS)}-{year}-W{week:02d}",
            pub=_rfc822(as_of), desc=escape(desc)))
    now = _rfc822(as_of)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n' + GENERATED + "\n"
        '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">\n'
        "<channel>\n"
        "  <title>The Most Useful Site in the World</title>\n"
        f"  <link>{SITE}/</link>\n"
        f"  <description>{count} free browser tools — calculators, converters, "
        "generators and simulators. No sign-ups, no accounts, runs in your "
        "browser. Plus one animated music video a week.</description>\n"
        "  <language>en-gb</language>\n"
        "  <managingEditor>hello@themostusefulsiteintheworld.com (Russell Head)</managingEditor>\n"
        "  <webMaster>hello@themostusefulsiteintheworld.com (Russell Head)</webMaster>\n"
        f"  <lastBuildDate>{now}</lastBuildDate>\n"
        f"  <pubDate>{now}</pubDate>\n"
        "  <ttl>1440</ttl>\n"
        "  <image>\n"
        f"    <url>{SITE}/og-tools.png</url>\n"
        "    <title>The Most Useful Site in the World</title>\n"
        f"    <link>{SITE}/</link>\n"
        "    <width>1200</width>\n"
        "    <height>630</height>\n"
        "  </image>\n"
        f'  <atom:link href="{SITE}/feed.xml" rel="self" type="application/rss+xml" />\n'
        "  <copyright>CC-BY 4.0 — Russell Head, Luton UK</copyright>\n"
        "  <category>tools</category>\n"
        "  <category>utilities</category>\n"
        "  <category>free</category>\n"
        "  <category>calculators</category>\n\n"
        + "\n\n".join(items) + "\n\n</channel>\n</rss>\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser(description="Regenerate feed.xml.")
    ap.add_argument("--date", default=datetime.date.today().isoformat())
    ap.add_argument("--out", default=OUT)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    fresh = build(datetime.date.fromisoformat(args.date))
    if args.check:
        try:
            with open(args.out, encoding="utf-8") as fh:
                current = fh.read()
        except FileNotFoundError:
            print("feed.xml missing — run feeds.py", file=sys.stderr)
            return 1
        if current != fresh:
            print("feed.xml is out of date — run: python3 scripts/promo/feeds.py",
                  file=sys.stderr)
            return 1
        print("feed OK — matches generated output.")
        return 0
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(fresh)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
