// Guards the prerendered per-tool pages in tools/ (P1-R2 pilot): each page
// must carry unique crawlable content, a working live-tool embed, valid
// structured data — and no analytics (tool pages stay clean per D-007; the
// footprint question is P0-M3, not something a new page decides alone).
//
// Run with: node scripts/tests/tool-pages.test.js
'use strict';
const fs = require('fs');
const assert = require('assert');

const NL = String.fromCharCode(10);
const cards = JSON.parse(fs.readFileSync('cards/cards.json', 'utf8'));
const slugs = new Set(cards.map(c => c.name));

// page -> embedded card slug, read from the content source the generator
// renders from (scripts/tool-pages.json). One list, so a page can never exist
// in the JSON and be unguarded here, or be guarded here and absent from the
// generator. The rollout stays deliberately small — staff/OPEN.md P1-R2 ties
// the 10–25 expansion to Search Console evidence.
const source = JSON.parse(fs.readFileSync('scripts/tool-pages.json', 'utf8'));
const PAGES = {};
for (const page of source.pages) PAGES[page.path] = page.slug;

function unescapeEntities(s) {
  return s.replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'").replace(/&amp;/g, '&');
}

for (const [page, slug] of Object.entries(PAGES)) {
  assert(fs.existsSync(page), page + ' missing');
  const h = fs.readFileSync(page, 'utf8');
  assert(slugs.has(slug), page + ': card slug ' + slug + ' not in catalogue');

  // Live tool via the documented embed contract (chrome-free + height).
  assert(h.includes('tool.html?card=' + slug + '&embed=1') ||
         h.includes('tool.html?card=' + slug + '&amp;embed=1'),
    page + ': must embed tool.html?card=' + slug + '&embed=1');
  assert(h.includes("d.card === '" + slug + "'") && h.includes('tmusitw:height'),
    page + ': must listen for the embed height postMessage for its own card');
  assert(h.includes('tool.html?card=' + slug + '">Open the standalone tool'),
    page + ': needs a no-JS fallback link to the standalone tool');

  // Crawlable metadata.
  assert(h.includes('<link rel="canonical" href="https://www.themostusefulsiteintheworld.com/' + page + '">'),
    page + ': self-referencing canonical required');
  assert(h.includes('name="description"') && h.includes('property="og:title"'),
    page + ': description + OG tags required');

  // Structured data must parse, with all three blocks.
  const blocks = [];
  const MARK = 'application/ld+json">';
  let at = 0;
  while (true) {
    const s = h.indexOf(MARK, at);
    if (s === -1) break;
    const e = h.indexOf('</script>', s);
    assert(e !== -1, page + ': unterminated JSON-LD block');
    blocks.push(h.slice(s + MARK.length, e));
    at = e;
  }
  assert(blocks.length >= 3, page + ': expected WebApplication + FAQPage + BreadcrumbList');
  const types = blocks.map(b => JSON.parse(b)['@type']);
  for (const t of ['WebApplication', 'FAQPage', 'BreadcrumbList']) {
    assert(types.includes(t), page + ': missing ' + t + ' JSON-LD');
  }
  const faq = JSON.parse(blocks[types.indexOf('FAQPage')]);
  assert(faq.mainEntity.length >= 4, page + ': FAQ needs 4+ questions');

  // Unique content, not a shell: worked example + caveat + author + date.
  for (const need of ['id="worked-example"', 'role="note"', 'Russell Head', '<time datetime="']) {
    assert(h.includes(need), page + ': missing ' + need);
  }
  // Visible copy must be substantial (pilot bar: 400+ words of article text).
  const text = h.replace(/<script[\s\S]*?<\/script>/g, '').replace(/<style[\s\S]*?<\/style>/g, '')
    .replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ');
  assert(text.split(' ').length >= 400, page + ': article copy below 400 words');

  // Claim hygiene on a YMYL-adjacent page: caveats present, no banned absolutes.
  // The intent is "a YMYL page says plainly that it is not advice" — so
  // "not advice", "not medical advice", "not a diagnosis" and "screening
  // tool" all satisfy it. The BMR page is a health page and words it as
  // medical advice; that is the honest phrasing, not a loophole.
  assert(/\bnot (?:medical |financial |legal )?advice\b|not a diagnosis|screening tool/i.test(h),
    page + ': needs an advice caveat');

  // Generated artefact: the page must carry the marker, and the FAQ rendered
  // on the page must be the SAME text as the FAQPage structured data. Before
  // the generator, a hand-edit changed one and not the other on a live page —
  // Google requires the structured data to match what a reader sees.
  assert(h.includes('<!-- generated by scripts/build-tool-pages.py'), page + ': missing generated-file marker');
  
  const visible = [];
  const DETAILS = '<details class="gfaq"><summary><strong>';
  let d = 0;
  while (true) {
    const s = h.indexOf(DETAILS, d);
    if (s === -1) break;
    const mid = h.indexOf('</strong></summary><p>', s);
    const end = h.indexOf('</p></details>', mid);
    assert(mid !== -1 && end !== -1, page + ': malformed FAQ markup');
    visible.push([unescapeEntities(h.slice(s + DETAILS.length, mid)),
                  unescapeEntities(h.slice(mid + '</strong></summary><p>'.length, end))]);
    d = end;
  }
  assert(visible.length >= 4, page + ': needs 4+ visible FAQ entries');
  const structured = faq.mainEntity.map(q => [q.name, q.acceptedAnswer.text]);
  assert(visible.length === structured.length, page + ': FAQ count differs between page and JSON-LD');
  for (let i = 0; i < visible.length; i++) {
    assert(visible[i][0] === structured[i][0],
      page + ': FAQ question ' + (i + 1) + ' differs between the page and the structured data');
    assert(visible[i][1] === structured[i][1],
      page + ': FAQ answer ' + (i + 1) + ' differs between the page and the structured data');
  }

  // Analytics footprint: tool pages load nothing (D-007). If the owner later
  // ratifies measurement here (P0-M3), this assertion changes with the ruling.
  assert(!h.includes('googletagmanager') && !h.includes('gtag('),
    page + ': tool pages must not load analytics without an owner ruling');

  console.log('  ok   ' + page + ': embed, metadata, JSON-LD, copy bar, no analytics');
}

console.log(NL + 'tool page tests passed');
