#!/usr/bin/env python3
"""build-tool-pages.py — render the static per-tool pages in tools/ from
scripts/tool-pages.json.

    python3 scripts/build-tool-pages.py           # (re)write tools/*.html
    python3 scripts/build-tool-pages.py --check   # fail if any page has drifted

Why these pages exist: every tool in the catalogue is a fragment behind
`tool.html?card=<slug>` — a query-param URL rendered by JavaScript, which a
non-JS crawler reads as an empty shell. staff/OPEN.md P1-R2 calls that the
single biggest GEO/discovery gap. These pages are the fix for a bounded,
chosen set of tools: a real URL, unique crawlable content, SoftwareApplication
+ FAQPage + BreadcrumbList structured data, and the live tool embedded from the
same card fragment (which stays the single implementation — never fork it).

Two rules this script exists to enforce:

1. **The content source is data, the chrome is code.** Chrome (head, CSS,
   footer, embed script) lives here; everything a writer edits lives in
   scripts/tool-pages.json. Rendering the same JSON must produce the same
   bytes, or --check fails.
2. **Published numbers are derived, never typed** (staff/DECISIONS.md D-001).
   A page may declare a `compute` block; the numbers in its prose come from
   {{placeholders}} filled by the arithmetic here, from its own inputs. A
   leftover {{...}} is a hard error, so a page can never ship a template gap.

Generated pages deliberately carry NO analytics: tool pages stay clean per
D-007, and adding GA here is an owner decision (P0-M3), not a generator flag.
"""
from __future__ import annotations

import argparse
import html
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = "https://www.themostusefulsiteintheworld.com"
# The JSON ends with "-interest.html" because its slug in the catalogue is
# `compoundinterest` while the page path spells the word out. Keep the two
# apart: the slug is what the card fragment is called.
SOURCE = os.path.join(ROOT, "scripts", "tool-pages.json")
CARDS = os.path.join(ROOT, "cards", "cards.json")
TOOLS_DIR = os.path.join(ROOT, "tools")

MARKER = "<!-- generated by scripts/build-tool-pages.py — edit scripts/tool-pages.json -->"

HEAD_TOP = '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n'

CSS = "\n*{margin:0;padding:0;box-sizing:border-box}\n:root{--accent:#2dd4ff;--text:#e6faff;--text-secondary:rgba(230,250,255,.7);--bg-primary:#0a0f14;--bg-secondary:#141e28;--border-light:rgba(255,255,255,.08);--gold:#ffd700;--success:#39ff14}\nbody{background:var(--bg-primary);color:var(--text);line-height:1.7;font-family:'Inter',system-ui,-apple-system,'Segoe UI',sans-serif;overflow-x:hidden}\na{color:inherit}\n.wrap{max-width:860px;margin:0 auto;padding:0 20px}\n.topbar{border-bottom:1px solid var(--border-light);padding:13px 0;background:rgba(10,15,20,.9);position:sticky;top:0;z-index:100;-webkit-backdrop-filter:blur(12px);backdrop-filter:blur(12px)}\n.topbar .wrap{display:flex;justify-content:space-between;align-items:center;gap:14px;max-width:1180px}\n.topbar a{text-decoration:none;font-weight:800;font-size:.9rem}.topbar .back{color:var(--text-secondary);font-weight:600;font-size:.85rem}.topbar .back:hover{color:var(--text)}\n.hero{padding:50px 0 24px;background:radial-gradient(ellipse 60% 50% at 50% 0%, rgba(45,212,255,0.08), transparent 70%)}\n.hero .eyebrow{display:inline-block;font-size:.7rem;font-weight:800;letter-spacing:.18em;text-transform:uppercase;color:var(--accent);border:1px solid rgba(45,212,255,.34);background:rgba(45,212,255,.07);padding:5px 12px;border-radius:100px;margin-bottom:14px}\n.hero h1{font-size:clamp(1.7rem,4.4vw,2.5rem);font-weight:900;letter-spacing:-.02em;line-height:1.2;color:#fff;margin-bottom:14px}\n.hero .lede{font-size:1.05rem;color:#d4e7ee;max-width:760px;line-height:1.7}\narticle{margin:30px 0}\narticle h2{font-size:1.4rem;font-weight:800;margin:36px 0 12px;color:#fff;scroll-margin-top:60px;line-height:1.3}\narticle p{margin:0 0 14px;color:#d4e7ee;font-size:1.02rem;line-height:1.75}\narticle p strong{color:#fff}\narticle a{color:var(--accent);text-decoration:underline;text-decoration-color:rgba(45,212,255,.4);text-underline-offset:2px}\narticle a:hover{text-decoration-color:var(--accent)}\narticle ol,article ul{margin:0 0 14px 22px;color:#d4e7ee;font-size:1.02rem;line-height:1.75}\narticle li{margin-bottom:6px}\n.tldr{background:linear-gradient(135deg, rgba(255,215,0,0.07), transparent);border:1px solid rgba(255,215,0,.3);border-left:3px solid var(--gold);border-radius:0 12px 12px 0;padding:18px 22px;margin:20px 0}\n.tldr h3{margin:0 0 8px;color:#fff;font-size:1.05rem}\n.tldr p{margin:0;font-size:.95rem;line-height:1.65}\n.tool-frame{border:1px solid rgba(45,212,255,.25);border-radius:14px;overflow:hidden;background:var(--bg-secondary);margin:16px 0}\n.tool-frame iframe{width:100%;height:520px;border:none;display:block}\n.tool-fallback{padding:10px 16px;font-size:.85rem;color:var(--text-secondary);border-top:1px solid var(--border-light)}\n.caveat{background:rgba(255,215,0,.05);border:1px solid rgba(255,215,0,.25);border-radius:12px;padding:16px 20px;margin:20px 0;font-size:.94rem;color:#d4e7ee}\n.caveat strong{color:#fff}\n.tools-block{margin:30px 0;padding:24px;background:linear-gradient(135deg, rgba(45,212,255,0.05), rgba(57,255,20,0.03));border:1px solid rgba(45,212,255,.2);border-radius:14px}\n.tools-block h2{margin:0 0 14px;color:#fff;font-size:1.15rem}\n.tools-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px;margin-top:10px}\n.gtool{background:rgba(20,30,40,.6);border:1px solid var(--border-light);border-radius:10px;padding:12px 14px;text-decoration:none;color:inherit;transition:all .2s;display:block}\n.gtool:hover{border-color:var(--accent);background:rgba(45,212,255,.06);text-decoration:none;color:inherit;transform:translateY(-2px);box-shadow:0 6px 16px rgba(0,0,0,.3)}\n.gt-emoji{font-size:1.3rem;margin-bottom:4px}\n.gt-name{font-size:.88rem;font-weight:700;color:#fff;margin-bottom:3px;line-height:1.3}\n.gt-desc{font-size:.74rem;color:var(--text-secondary);line-height:1.45;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}\n.faq-block{margin:36px 0;padding:24px;background:var(--bg-secondary);border:1px solid var(--border-light);border-radius:14px}\n.faq-block h2{margin:0 0 14px;color:#fff;font-size:1.2rem}\n.gfaq{background:rgba(10,15,20,.5);border:1px solid var(--border-light);border-radius:8px;padding:11px 14px;margin:8px 0}\n.gfaq summary{cursor:pointer;font-size:.95rem;color:#fff;list-style:none}\n.gfaq summary::-webkit-details-marker{display:none}\n.gfaq p{margin:8px 0 0;color:#d4e7ee;font-size:.94rem;line-height:1.6}\n.cta{margin:36px 0;padding:24px;border-radius:14px;background:linear-gradient(135deg, rgba(45,212,255,0.08), rgba(255,215,0,0.04));border:1px solid rgba(45,212,255,.2);text-align:center}\n.cta a{display:inline-flex;align-items:center;gap:8px;padding:11px 22px;border-radius:100px;background:var(--accent);color:#04141c;font-weight:800;font-size:.93rem;text-decoration:none;margin:4px}\n.cta a.alt{background:transparent;border:1px solid var(--border-light);color:#e6faff}\nfooter{border-top:1px solid var(--border-light);margin-top:50px;padding:24px 0;text-align:center;color:var(--text-secondary);font-size:.85rem}footer a{text-decoration:none;margin:0 8px}footer a:hover{color:var(--text)}\n@media(prefers-reduced-motion:reduce){*{transition:none!important}}\n"

TOPBAR = '<div class="topbar"><div class="wrap">\n  <a href="../index.html">🛠️ The Most Useful Site in the World</a>\n  <a class="back" href="../index.html">← Back to the tools</a>\n</div></div>'

FOOTER_JS = '<footer><div class="wrap">\n  <p><a href="../index.html">All __COUNT__ tools</a>·<a href="../about.html">About</a>·<a href="../press.html">Press</a>·<a href="../tools.html">Index</a>·<a href="../popular.html">Popular</a>·<a href="../new.html">New</a>·<a href="../use-case.html">Use case</a>·<a href="../help.html">Help</a>·<a href="../changelog.html">Changelog</a>·<a href="../embed.html">Embed</a>·<a href="../sitemap.html">Sitemap</a>·<a href="../blog/">Blog</a>·<a href="../donate.html">Donate</a>·<a href="../sponsor.html">Sponsor</a>·<a href="../listen.html">Music</a></p>\n</div></footer>\n\n<script>\n// Auto-size the embedded tool: tool.html?card=<slug>&embed=1 posts its height.\nwindow.addEventListener(\'message\', function (e) {\n  if (e.origin !== window.location.origin) return;\n  var d = e.data || {};\n  if (d.type === \'tmusitw:height\' && d.card === \'__SLUG__\' && d.height > 0) {\n    document.getElementById(\'tool-frame\').style.height = Math.min(d.height, 4000) + \'px\';\n  }\n});\n</script>\n\n</body></html>'

FAVICON = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Cdefs%3E%3ClinearGradient id='g' x1='0' y1='0' x2='1' y2='1'%3E%3Cstop offset='0' stop-color='%23ffd400'/%3E%3Cstop offset='1' stop-color='%23ff9500'/%3E%3C/linearGradient%3E%3C/defs%3E%3Ccircle cx='16' cy='16' r='13' fill='none' stroke='url(%23g)' stroke-width='5'/%3E%3Ccircle cx='16' cy='16' r='6' fill='none' stroke='url(%23g)' stroke-width='3'/%3E%3C/svg%3E"


# --------------------------------------------------------------------------
# Derived numbers (D-001). Every helper returns already-formatted strings so a
# writer never hand-formats a figure into prose.
# --------------------------------------------------------------------------
def money(value: float) -> str:
    """£1,389.58 — the house format for money on these pages."""
    return "£" + format(round(value, 2), ",.2f")


def money0(value: float) -> str:
    """£166,874 — whole pounds, for totals where pennies are noise."""
    return "£" + format(round(value), ",.0f")


def num(value: float) -> str:
    """1,649 — comma-grouped whole number, matching the cards' toLocaleString()
    so the page and the tool show the same digits."""
    return format(round(value), ",d")


def amortise(principal: float, annual_rate_pct: float, years: float, extra: float = 0.0) -> dict:
    """Repayment loan, straight from the formula the page prints:
    P·i·(1+i)^n / ((1+i)^n − 1), then month by month for the totals, with any
    extra payment hitting principal. Mirrors cards/loan.html — the tool the
    page embeds — so the page and the tool cannot disagree. Raw numbers only;
    formatting is the caller's job."""
    n = int(round(years * 12))
    i = annual_rate_pct / 100.0 / 12.0
    payment = principal / n if i == 0 else principal * i * (1 + i) ** n / ((1 + i) ** n - 1)
    balance, interest_total, paid_total, months = principal, 0.0, 0.0, 0
    for month in range(1, n + 1):
        if balance <= 0:
            break
        interest = balance * i
        principal_paid = min((payment - interest) + extra, balance)
        balance -= principal_paid
        interest_total += interest
        paid_total += interest + principal_paid
        months = month
    i_month = principal * i if months else 0.0
    return {"n": n, "payment": payment, "total_paid": paid_total,
            "total_interest": interest_total, "months": months,
            "first_interest": i_month}


def loan_block(p: dict) -> dict:
    base = amortise(p["principal"], p["annual_rate"], p["years"])
    values = {
        "amount": money0(p["principal"]),
        "principal": money0(p["principal"]),
        "rate": f"{p['annual_rate']:g}",
        "years": f"{p['years']:g}",
        "months": str(base["n"]),
        "payment": money(base["payment"]),
        "payment_0dp": money0(base["payment"]),
        "total_paid": money0(base["total_paid"]),
        "total_interest": money0(base["total_interest"]),
        "first_interest": money(base["first_interest"]),
        "first_interest_share": f"{base['first_interest'] / base['payment'] * 100:.0f}%",
    }
    if p.get("extra_monthly"):
        extra = p["extra_monthly"]
        with_extra = amortise(p["principal"], p["annual_rate"], p["years"], extra)
        values.update({
            "extra": money0(extra),
            "term_with_extra": f"{with_extra['months'] / 12:.1f}".rstrip("0").rstrip("."),
            "interest_with_extra": money0(with_extra["total_interest"]),
            "interest_saved": money0(base["total_interest"] - with_extra["total_interest"]),
        })
    return values


def bmr_block(p: dict) -> dict:
    """Mifflin-St Jeor, exactly as cards/bmr.html implements it:
    men 10w + 6.25h − 5a + 5 · women 10w + 6.25h − 5a − 161."""
    w, h, a = p["kg"], p["cm"], p["age"]
    male = (10 * w) + (6.25 * h) - (5 * a) + 5
    female = (10 * w) + (6.25 * h) - (5 * a) - 161
    out = {
        "kg": f"{w:g}", "cm": f"{h:g}", "age": f"{a:g}",
        "bmr_male": num(male), "bmr_female": num(female),
    }
    mult = {"sedentary": 1.2, "light": 1.375, "moderate": 1.55, "active": 1.725, "athlete": 1.9}
    for name, factor in mult.items():
        out["tdee_" + name] = num((male if p.get('sex', 'male') == 'male' else female) * factor)
    return out


def percent_block(p: dict) -> dict:
    value, pct = p["value"], p["percent"]
    out = {
        "value": f"{value:g}",
        "percent": f"{pct:g}",
        "of": f"{value * pct / 100:g}",
        "increase": f"{value * (1 + pct / 100):,.2f}".rstrip("0").rstrip("."),
        "decrease": f"{value * (1 - pct / 100):,.2f}".rstrip("0").rstrip("."),
    }
    if p.get("from") and p.get("to"):
        f, t = p["from"], p["to"]
        out.update({
            "from": f"{f:g}", "to": f"{t:g}",
            "change_pct": f"{(t - f) / f * 100:.1f}".rstrip("0").rstrip("."),
            "change_direction": "increase" if t > f else "decrease",
        })
    return out


KINDS = {"loan": loan_block, "bmr": bmr_block, "percent": percent_block}

PLACEHOLDER = re.compile(r"\{\{([a-z0-9_]+)\}\}")


def esc(text: str) -> str:
    """Plain text going into HTML: the JSON stores prose unescaped, so a bare
    & in a title becomes &amp; here rather than in every hand-edit."""
    return html.escape(text, quote=True)


def frag(text: str) -> str:
    """HTML fragment: keep the inline markup, escape only bare ampersands."""
    return re.sub(r"&(?!(?:[A-Za-z][A-Za-z0-9]*|#\d+|#x[0-9A-Fa-f]+);)", "&amp;", text)


def fill(where: str, text: str, values: dict) -> str:
    """Substitute {{key}}; a missing or leftover placeholder is a hard error."""
    def sub(m):
        key = m.group(1)
        if key not in values:
            raise SystemExit(f"{where}: prose needs {{{{{key}}}}} but the compute block does not define it")
        return str(values[key])
    filled = PLACEHOLDER.sub(sub, text)
    if PLACEHOLDER.search(filled):
        raise SystemExit(f"{where}: unresolved placeholder left in rendered text")
    return filled


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------
def ld(obj) -> str:
    return json.dumps(obj, ensure_ascii=False, separators=(", ", ": "))


def render(page: dict, count: int) -> str:
    slug, path = page["slug"], page["path"]
    canonical = f"{SITE}/{path}"
    values = {}
    if page.get("compute"):
        kind = page["compute"]["kind"]
        if kind not in KINDS:
            raise SystemExit(f"{path}: unknown compute kind {kind!r}")
        try:
            values = KINDS[kind](page["compute"])
        except KeyError as exc:
            raise SystemExit(f"{path}: compute block is missing {exc}")

    def F(text: str) -> str:
        return fill(path, text, values)

    webapp = {
        "@context": "https://schema.org",
        "@type": "WebApplication",
        "name": page["h1"],
        "url": canonical,
        "description": page["schema_description"],
        "applicationCategory": page["application_category"],
        "operatingSystem": "Any (web browser)",
        "offers": {"@type": "Offer", "price": "0", "priceCurrency": "GBP"},
        "author": {"@type": "Person", "name": "Russell Head", "url": f"{SITE}/about.html"},
    }
    faq = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {"@type": "Question", "name": F(q["q"]),
             "acceptedAnswer": {"@type": "Answer", "text": F(q["a"])}}
            for q in page["faq"]
        ],
    }
    crumbs = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": f"{SITE}/"},
            {"@type": "ListItem", "position": 2, "name": "Tools", "item": f"{SITE}/tools-index.html"},
            {"@type": "ListItem", "position": 3, "name": page["h1"], "item": canonical},
        ],
    }

    steps = "\n".join(f"  <li>{frag(F(s))}</li>" for s in page["steps"])
    limits = "\n".join(f"  <li>{frag(F(s))}</li>" for s in page["limits"])
    related = "\n".join(
        '    <a class="gtool" href="../tool.html?card={slug}"><div class="gt-emoji">{emoji}</div>'
        '<div class="gt-name">{name}</div><div class="gt-desc">{desc}</div></a>'.format(
            slug=esc(r["slug"]), emoji=esc(r["emoji"]), name=esc(r["name"]), desc=esc(r["desc"]))
        for r in page["related"]
    )
    faqs = "\n".join(
        f'  <details class="gfaq"><summary><strong>{esc(F(q["q"]))}</strong></summary><p>{frag(F(q["a"]))}</p></details>'
        for q in page["faq"]
    )
    cta = [f'  <a href="../index.html">🔲 Browse all {count} tools</a>',
           '  <a class="alt" href="../tools.html">📚 Full index</a>']
    if page.get("guide"):
        cta.append(f'  <a class="alt" href="../guides/{page["guide"]}.html">📖 The full guide</a>')
    cta.append('  <a class="alt" href="../embed.html">🔌 Embed this tool</a>')
    cta = "\n".join(cta)
    guide_line = (f'\n  <p style="margin-top: 12px; color: var(--text-secondary); font-size: .9rem;">'
                  f'📖 Long-form companion: <a href="../guides/{page["guide"]}.html" '
                  f'style="color: var(--accent);">{esc(page["guide_label"])}</a>.</p>' if page.get("guide") else "")

    return f"""{HEAD_TOP}<link rel="icon" href="{page.get('favicon', FAVICON)}">
<title>{esc(page["title"])}</title>
<meta name="description" content="{esc(page["description"])}">
<meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large">
<link rel="canonical" href="{canonical}">
<link rel="alternate" type="application/rss+xml" title="The Most Useful Site in the World — RSS feed" href="../feed.xml">
<meta name="theme-color" content="#0a0f14">
<meta property="og:type" content="website">
<meta property="og:site_name" content="The Most Useful Site in the World">
<meta property="og:title" content="{esc(page["og_title"])}">
<meta property="og:description" content="{esc(page["og_description"])}">
<meta property="og:url" content="{canonical}">
<meta property="og:image" content="{SITE}/og-tools.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{esc(page["twitter_title"])}">
<meta name="twitter:description" content="{esc(page["twitter_description"])}">
<meta name="twitter:image" content="{SITE}/og-tools.png">
<meta name="author" content="Russell Head">
<script type="application/ld+json">{ld(webapp)}</script>
<script type="application/ld+json">{ld(faq)}</script>
<script type="application/ld+json">{ld(crumbs)}</script>
<style>
{CSS.strip()}
</style>
</head>
<body>
{MARKER}

{TOPBAR}

<header class="hero"><div class="wrap">
  <div class="eyebrow">{esc(page["category"])} · Free tool</div>
  <h1>{esc(page["h1"])}</h1>
  <p class="lede">{esc(page["lede"])}</p>
  <p style="font-size:.82rem;color:var(--text-secondary);">Last updated: <time datetime="{page["updated"]}">{esc(page["updated_label"])}</time> · By <a href="../about.html" style="color:inherit;">Russell Head</a></p>
</div></header>

<main class="wrap"><article>

<div class="tldr">
  <h3>⚡ The short version</h3>
  {frag(F(page["tldr"]))}
</div>

<h2 id="calculator">The calculator</h2>
<div class="tool-frame">
  <iframe id="tool-frame" src="../tool.html?card={slug}&amp;embed=1" title="{esc(page["iframe_title"])}" loading="eager"></iframe>
  <div class="tool-fallback">{frag(F(page["fallback"]))}</div>
</div>

<h2 id="how-to-use">How to use it</h2>
<ol>
{steps}
</ol>

<h2 id="worked-example">Worked example</h2>
{frag(F(page["worked"]))}

<div class="caveat" role="note">{frag(F(page["caveat"]))}</div>

<h2 id="what-it-misses">{page["limits_heading"]}</h2>
<ul>
{limits}
</ul>

<div class="tools-block">
  <h2>{page["related_heading"]}</h2>
  <div class="tools-grid">
{related}
  </div>{guide_line}
</div>

<div class="faq-block">
  <h2>❓ Frequently asked questions</h2>
{faqs}
</div>

<div class="cta">
  <p style="margin:0 0 12px;color:#fff;font-size:1rem;font-weight:700;">Keep exploring</p>
{cta}
</div>

</article></main>

{FOOTER_JS.replace('__COUNT__', str(count)).replace('__SLUG__', slug)}
"""


# --------------------------------------------------------------------------
# Validation of the source data
# --------------------------------------------------------------------------
def visible_words(html_text: str) -> int:
    text = re.sub(r"<script[\s\S]*?</script>", " ", html_text)
    text = re.sub(r"<style[\s\S]*?</style>", " ", text)
    text = re.sub(r"<[^>]+>", " ", text)
    return len(re.sub(r"\s+", " ", text).split())


def load_source() -> tuple[list[dict], dict]:
    with open(SOURCE, encoding="utf-8") as fh:
        source = json.load(fh)
    with open(CARDS, encoding="utf-8") as fh:
        cards = json.load(fh)
    return source["pages"], {c["name"]: c for c in cards}


def validate(pages: list[dict], catalogue: dict, count: int) -> list[str]:
    problems, paths, titles = [], set(), set()
    for page in pages:
        path = page["path"]
        def bad(msg):
            problems.append(f"{path}: {msg}")
        if page["slug"] not in catalogue:
            bad(f"card slug {page['slug']!r} is not in cards.json")
        if path in paths:
            bad("duplicate path")
        paths.add(path)
        if page["title"] in titles:
            bad("duplicate <title> — thin/duplicate pages are worse than none")
        titles.add(page["title"])
        if len(page["faq"]) < 4:
            bad("needs 4+ FAQ entries (they become FAQPage structured data)")
        for field in ("tldr", "worked", "caveat", "lede"):
            if not page.get(field):
                bad(f"missing {field}")
        for ref in page.get("related", []):
            if ref["slug"] not in catalogue:
                bad(f"related slug {ref['slug']!r} is not in cards.json")
        if page.get("compute"):
            # exercise the arithmetic now, so a broken formula fails the build
            try:
                render(page, count)
            except SystemExit as exc:
                problems.append(str(exc))
        body = render(page, count)
        if visible_words(body) < 400:
            bad(f"only {visible_words(body)} words of visible text (bar is 400)")
        for banned in ("googletagmanager", "gtag(", "dQw4w9WgXcQ", "VIDEO_ID", "PLAYLIST_ID"):
            if banned in body:
                bad(f"contains {banned!r}")
        if MARKER not in body:
            bad("missing the generated-file marker")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when a rendered page differs from disk")
    args = parser.parse_args()

    pages, catalogue = load_source()
    count = len(catalogue)
    problems = validate(pages, catalogue, count)
    if problems:
        for problem in problems:
            print("  FAIL " + problem, file=sys.stderr)
        return 1

    os.makedirs(TOOLS_DIR, exist_ok=True)
    drifted, written = [], 0
    for page in sorted(pages, key=lambda p: p["path"]):
        out = render(page, count)
        target = os.path.join(ROOT, page["path"])
        current = open(target, encoding="utf-8").read() if os.path.exists(target) else None
        if current == out:
            continue
        if args.check:
            drifted.append(page["path"])
            continue
        with open(target, "w", encoding="utf-8") as fh:
            fh.write(out)
        written += 1

    declared = {page["path"] for page in pages}
    on_disk = {f"tools/{n}" for n in os.listdir(TOOLS_DIR) if n.endswith(".html")}
    orphans = sorted(on_disk - declared)
    if orphans:
        print("  FAIL tools/ page(s) not in scripts/tool-pages.json: " + ", ".join(orphans), file=sys.stderr)
        print("       add them to the JSON (or delete them) — a hand-written page here drifts silently", file=sys.stderr)
        return 1

    if args.check:
        if drifted:
            print("tool pages are stale — run: python3 scripts/build-tool-pages.py", file=sys.stderr)
            for path in drifted:
                print("  drift " + path, file=sys.stderr)
            return 1
        print(f"tool pages OK — {len(pages)} page(s) match scripts/tool-pages.json")
        return 0

    print(f"tool pages: {written} written, {len(pages)} declared, {count} tools in the catalogue")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
