#!/usr/bin/env python3
"""build-home-prerender.py — keep index.html's first-screen fast path in sync.

    python3 scripts/build-home-prerender.py           # rewrite both blocks
    python3 scripts/build-home-prerender.py --check   # fail on drift (verify.sh)

What it generates
-----------------
Two blocks in `index.html`, both derived from `cards/cards.json` and both
delimited by marker comments:

1. `HOME-FAST-PATH` (in `<head>`) — a bootstrap that starts the catalogue
   index fetch and the first `FETCH` card-fragment fetches while the head is
   still being parsed. The responses are held as promises and consumed exactly
   once by the loader, so this cannot double-download.

2. `HOME-PRERENDER` (in `#dashboard`) — the first `MARKUP` card shells as real
   markup: title, category badge and standalone link. They paint with the HTML
   instead of after a 516 KB JSON round trip, and `adoptPrerenderedCards()`
   adopts them rather than rebuilding them.

It also re-syncs the per-category count badges on the filter pills. Those are
not a performance concern — they are the same class of bug: 21 of the 27 counts
had drifted (they summed to 1839 for a 1128-tool catalogue). `updateCategoryCounts()`
overwrites them from cards.json at runtime, so the drift was invisible in a
browser and visible to every crawler and no-JS visitor. `count-all` and
`heroToolCount` are deliberately left to `sync-counts.py`, which already claims
them (CHROME_COUNT); two owners for one number is how the count got out of sync
49 times in the first place.

Why it exists
-------------
The home page used to render nothing but anonymous skeletons until
`cards/cards.json` (516 KB raw / 136 KB gzipped) had downloaded *and* parsed,
and the first tool fragment was not even requested until that was done: on a
modelled fast-4G link the first real card landed ~745 ms in, behind 194 KB of
bytes it did not depend on. Both blocks remove that serialisation.

The card order is the same order the page uses at runtime
(`Array.from(cardsMetaMap.keys()).sort()` — plain slug sort, ASCII), so the
shells the browser paints are the shells the loader would have built.

Like `sync-counts.py` and `build-sitemap.py`, this is a generated artefact with
a `--check`: a rule a human has to remember is a rule that breaks. After adding
or removing a tool, run `node generate-cards-json.js` and then this script —
`scripts/verify.sh` fails if the blocks have drifted from the catalogue.
"""
from __future__ import annotations

import argparse
import html
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "index.html")
CARDS_JSON = os.path.join(ROOT, "cards", "cards.json")

# How many first-screen card shells to pre-render, and how many of those to
# start fetching in <head>. FETCH matches CONFIG.INITIAL_LOAD's floor (6) —
# the loader asks for exactly that many on a normal viewport, and every extra
# prefetch is bandwidth taken from cards.json.
MARKUP = 8
FETCH = 6

FAST_PATH = ("<!--HOME-FAST-PATH:BEGIN", "<!--HOME-FAST-PATH:END-->")
PRERENDER = ("<!--HOME-PRERENDER:BEGIN", "<!--HOME-PRERENDER:END-->")


def slug_sort_key(name: str):
    """Match JavaScript's default Array#sort (UTF-16 code units).

    Card slugs are ASCII `[a-z0-9-]`, where code-unit and code-point order
    agree, so this is a plain sort — but the assert keeps a future
    non-ASCII slug from silently reordering the first screen.
    """
    return name


def load_catalogue() -> list[dict]:
    with open(CARDS_JSON, encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data, list) or not data:
        sys.exit("build-home-prerender.py: cards/cards.json is empty or not a list")
    by_name: dict[str, dict] = {}
    for item in data:
        name = item.get("name") or item.get("id") or ""
        name = re.sub(r"\.html$", "", str(name))
        if name:
            by_name[name] = item
    names = sorted(by_name, key=slug_sort_key)
    for n in names[:MARKUP]:
        if not re.fullmatch(r"[a-zA-Z0-9._-]+", n):
            sys.exit(f"build-home-prerender.py: first-screen slug {n!r} is not URL-safe")
    return [by_name[n] for n in names]


def js_array(names: list[str]) -> str:
    return "[" + ", ".join('"%s"' % n for n in names) + "]"


def fast_path_block(catalogue: list[dict]) -> str:
    names = [c["name"] for c in catalogue[:FETCH]]
    return f"""{FAST_PATH[0]} — generated by scripts/build-home-prerender.py. Do not hand-edit.-->
    <script>
    /* First-screen bootstrap. This runs while <head> is still being parsed, so
       the catalogue index and the fragments behind the pre-rendered cards in
       #dashboard are already in flight long before the app script at the end of
       <body> exists — the first tools no longer wait for cards.json.
       Each response is a promise consumed exactly once (takePrefetchedCard /
       __mpFastPath.json), which is why this replaced a
       <link rel="preload" as="fetch">: reusing a preload depends on its
       credentials mode matching the later fetch(), and a miss downloads
       136 KB twice. Failure here is silent — the loader fetches for itself. */
    (() => {{
        const FIRST_SCREEN = {js_array(names)};
        try {{
            const fp = window.__mpFastPath = {{ json: null, cards: new Map() }};
            const opts = {{ credentials: 'same-origin', priority: 'high' }};
            const asText = p => p.then(r => (r && r.ok ? r.text() : null)).catch(() => null);
            fp.json = asText(fetch('cards/cards.json', opts));
            FIRST_SCREEN.forEach(name => fp.cards.set(name, asText(fetch('cards/' + name + '.html', opts))));
        }} catch (err) {{ /* no fetch (file://) or blocked: loader falls back */ }}
    }})();
    </script>
    {FAST_PATH[1]}"""


def prerender_block(catalogue: list[dict]) -> str:
    """Card shells byte-identical in structure to createPlaceholder()'s output."""
    shells = []
    for card in catalogue[:MARKUP]:
        name = card["name"]
        title = html.escape(card.get("title") or name.replace("-", " ").title(), quote=True)
        category = html.escape(card.get("category") or "Productivity & Lifestyle", quote=True)
        href = "tool.html?card=" + html.escape(name, quote=True)
        bars = "<i></i>" * 7
        shells.append(f"""        <div class="card card-pending" data-name="{name}" data-display-name="{title}" data-category="{category}">
            <div class="card-header">
                <div class="card-header-info">
                    <h3>{title}</h3>
                    <span class="card-cat-badge">{category}</span>
                </div>
                <div class="card-actions">
                    <button class="card-action-btn add-grid" title="Add to Grid Mode">🔲</button>
                    <button class="card-action-btn add-list" title="Add to List Mode">📋</button>
                    <a href="{href}" target="_blank" rel="noopener" class="card-maximize-btn" title="Maximise to Standalone Tool" aria-label="Maximise {title} to standalone">
                        <span class="max-icon">⛶</span>
                        <span class="max-label">Standalone</span>
                    </a>
                </div>
            </div>
            <div class="card-content">
                <div class="card-sandbox" id="card-{name}">
                    <div class="card-skeleton" aria-hidden="true">
                        <div class="card-skeleton-bars">{bars}</div>
                        <div class="card-skeleton-text">{title}</div>
                    </div>
                </div>
            </div>
        </div>""")
    header = f"""{PRERENDER[0]} — generated by scripts/build-home-prerender.py. Do not
         hand-edit. Real first-screen card shells: they paint titles, category
         badges and standalone links with the HTML itself (no JS, no
         cards.json), and adoptPrerenderedCards() adopts them instead of
         rebuilding them, so the fragments the head bootstrap already fetched
         render straight into these. data-name is the catalogue slug and the
         sandbox id matches createPlaceholder()'s `card-<name>`. No card JS has
         run yet, so nothing here can collide in the shared DOM. -->"""
    return header + "\n" + "\n".join(shells) + f"\n        {PRERENDER[1]}"


PILL = re.compile(r'<button[^>]*\bdata-category="([^"]+)"[^>]*>')
BADGE = re.compile(r'(class="cat-count"\s+id="count-[A-Za-z0-9_-]+">)(\d+)(</span>)')


def category_counts(catalogue: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for card in catalogue:
        cat = card.get("category") or "Productivity & Lifestyle"
        counts[cat] = counts.get(cat, 0) + 1
    return counts


def find_badge_drift(source: str, counts: dict[str, int]):
    """[(category, in_html, in_catalogue, offset)] for every stale pill badge."""
    drift = []
    for pill in PILL.finditer(source):
        cat = pill.group(1)
        # count-all is sync-counts.py's claim (CHROME_COUNT). One number, one
        # owner: a second writer for it is how the count drifted 49 times.
        if cat == "all" or cat not in counts:
            continue
        badge = BADGE.search(source, pill.end(), pill.end() + 500)
        if badge and int(badge.group(2)) != counts[cat]:
            drift.append((cat, int(badge.group(2)), counts[cat], badge.start(2)))
    return drift


def sync_category_counts(source: str, counts: dict[str, int]) -> tuple[str, list]:
    drift = find_badge_drift(source, counts)
    # Rewrite from the end backwards so the earlier offsets stay valid.
    for _cat, old, new, offset in sorted(drift, key=lambda d: -d[3]):
        source = source[:offset] + str(new) + source[offset + len(str(old)):]
    return source, drift


def replace_block(source: str, markers: tuple[str, str], block: str, label: str) -> str:
    start = source.find(markers[0])
    end = source.find(markers[1])
    if start == -1 or end == -1 or end < start:
        sys.exit(
            f"build-home-prerender.py: cannot find the {label} markers in index.html.\n"
            f"  expected {markers[0]} ... {markers[1]}"
        )
    return source[:start] + block + source[end + len(markers[1]):]


def build() -> tuple[str, list]:
    with open(INDEX, encoding="utf-8") as fh:
        source = fh.read()
    catalogue = load_catalogue()
    out = replace_block(source, FAST_PATH, fast_path_block(catalogue), "HOME-FAST-PATH")
    out = replace_block(out, PRERENDER, prerender_block(catalogue), "HOME-PRERENDER")
    out, drift = sync_category_counts(out, category_counts(catalogue))
    return out, drift


def block_of(source: str, markers: tuple[str, str]) -> str:
    start = source.find(markers[0])
    end = source.find(markers[1])
    if start == -1 or end == -1:
        return ""
    return source[start:end + len(markers[1])]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if index.html's generated first screen is stale")
    args = ap.parse_args()

    with open(INDEX, encoding="utf-8") as fh:
        current = fh.read()
    expected, drift = build()
    counts = category_counts(load_catalogue())

    if current == expected:
        print(f"HOME PRERENDER OK — first {MARKUP} shells, {FETCH} bootstrap fetches "
              f"and {len(counts) - 1} category counts match cards.json")
        return 0

    stale = [label for label, markers in (("HOME-FAST-PATH", FAST_PATH), ("HOME-PRERENDER", PRERENDER))
             if block_of(current, markers) != block_of(expected, markers)]

    if args.check:
        print("HOME PRERENDER STALE — index.html's generated first screen does not match cards/cards.json")
        print("  fix with: python3 scripts/build-home-prerender.py")
        for label in stale:
            print(f"  stale block: {label}")
        for cat, was, should, _ in drift:
            print(f"  stale category count: {cat} says {was}, catalogue has {should}")
        if not stale and not drift:
            for i, (a, b) in enumerate(zip(current, expected)):
                if a != b:
                    print(f"  first difference at byte {i} (line {expected[:i].count(chr(10)) + 1})")
                    print(f"    in index.html: {current[i - 40:i + 60]!r}")
                    print(f"    should be:     {expected[i - 40:i + 60]!r}")
                    break
            else:
                print(f"  length differs: index.html {len(current)} vs generated {len(expected)}")
        return 1

    with open(INDEX, "w", encoding="utf-8") as fh:
        fh.write(expected)
    print(f"index.html updated — first {MARKUP} card shells + {FETCH} bootstrap fetches regenerated")
    for label in stale:
        print(f"  rewrote block: {label}")
    for cat, was, should, _ in drift:
        print(f"  category count: {cat} {was} -> {should}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
