#!/usr/bin/env python3
"""build-tool-fullpages.py — render a full HTML page for EVERY tool in tool/.

    python3 scripts/build-tool-fullpages.py           # (re)write tool/*.html
    python3 scripts/build-tool-fullpages.py --check   # fail if any page has drifted

Why these pages exist
---------------------
Until 2026-10-05 the only way to RUN a tool was `tool.html?card=<slug>` — one
shared, long-lived document that swaps card fragments in and out. Two costs:

1. **Breakage.** Globals, listeners, timers and styles survive one card into
   the next (CONSTRAINTS.md "Card traps"), so the shell needs a whole check
   fleet to stay honest, and a card can still break the tool after it.
2. **Discovery.** A query-param URL is a JS shell to a crawler: non-JS readers
   (and every AI index) see an empty page.

`tool/<slug>.html` is the fix for the whole catalogue at once: a real URL, one
document per tool. The card fragment is the single implementation and is
INLINED verbatim — no fetch, no iframe, no JavaScript required for the tool to
work, and nothing from one tool can survive into another because there is no
"other" in the document.

What the page adds around the card:
- first-class navigation: breadcrumbs, previous/next tool in the category, a
  ranked related-tools grid (related.json, padded from the category) and the
  category hub — a tool is a page in a collection, not an island;
- the site search (a plain form, zero JS), the saved toolbox (toolbox.js +
  toolbox.css, the same panel as every list page) and the YMYL risk notice
  (risk-notices.js, the same call tool.html makes);
- crawlable head: static title/description from the fragment, canonical, OG,
  WebApplication + BreadcrumbList JSON-LD.

What it deliberately does NOT replace: `tool.html?card=` stays the stateful
shell — `&embed=1` (the documented embed contract), filled links
(`&<control>=<value>&run=1`) and multi-step jobs all carry URL state that a
static page cannot answer. Every filled-link surface (jobs.json, intents.json,
the share panel) keeps pointing at the shell.

Two rules, the same as build-tool-pages.py:
1. **Rendering must be deterministic** — the same inputs produce the same
   bytes, or --check is useless. No timestamps, no randomness; ordering comes
   from the catalogue (title sort, slug tie-break) exactly as the category
   pages order their rows.
2. **Published numbers are derived, never typed.** The tool count and the
   per-category counts come from cards.json at build time.

The card is inlined, but two things are rewritten:
- markup `href`/`src` values that resolve from the SITE ROOT are rewritten to
  root-absolute (`ai.html#x` -> `/ai.html#x`) so a link a card wrote for the
  root-injected shell still lands from one directory down. Scripts are never
  touched; only real markup attributes.
- a card's `cards/<slug>.html` link (raw fragment) becomes the full page.

Nothing here leaves the device: no analytics on these pages (they are the
catalogue, Product A), no third-party scripts, no cookies. The only runtime
requests are the card's own (offline by rule) plus toolbox.js's lazy
cards-lite.json lookup, which the list pages already make.
"""
from __future__ import annotations

import argparse
import html
import json
import os
import re
import sys
import unicodedata

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = "https://www.themostusefulsiteintheworld.com"
CARDS_JSON = os.path.join(ROOT, "cards", "cards.json")
CARDS_DIR = os.path.join(ROOT, "cards")
RELATED_JSON = os.path.join(ROOT, "related.json")
OUT_DIR = os.path.join(ROOT, "tool")
SW_JS = os.path.join(ROOT, "sw.js")

MARKER = "<!-- generated by scripts/build-tool-fullpages.py — edit the card in cards/, not this file -->"

# --------------------------------------------------------------------------
# Small shared machinery, kept in sync with the rest of the build.
# --------------------------------------------------------------------------
def asset_version() -> int:
    """?v= for shared scripts. One home, CACHE_VERSION in sw.js — hard-coding
    it here is how tools.html once shipped explore.css?v=1 against a ?v=16
    homepage (the note in build-category-pages.js is the same incident)."""
    with open(SW_JS, encoding="utf-8") as fh:
        m = re.search(r"CACHE_VERSION\s*=\s*'v(\d+)-", fh.read())
    if not m:
        raise SystemExit("sw.js has no CACHE_VERSION = 'vN-<date>' — cannot version page assets")
    return int(m.group(1))


_TITLE_NOISE = re.compile(r"^[\s\W_]+", re.UNICODE)


def title_sort_key(title: str) -> str:
    """Byte-for-byte discovery_catalogue.title_sort_key: A–Z by title, emoji
    stripped, so previous/next follow the same order the category pages use."""
    stripped = _TITLE_NOISE.sub("", title or "")
    if not stripped:
        stripped = title or ""
    folded = unicodedata.normalize("NFKD", stripped)
    folded = "".join(ch for ch in folded if not unicodedata.combining(ch))
    return folded.casefold()


def slugify_category(name: str) -> str:
    """discovery_catalogue.slugify_category."""
    s = name.lower().replace("&", "and")
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def esc(text: str) -> str:
    return html.escape(str(text), quote=True)


def truncate(text: str, limit: int) -> str:
    text = re.sub(r"\s+", " ", str(text)).strip()
    if len(text) <= limit:
        return text
    cut = text[:limit].rsplit(" ", 1)[0].rstrip(",;:. ")
    return cut + "…"

# --------------------------------------------------------------------------
# Card fragment handling
# --------------------------------------------------------------------------
SCHEME_RE = re.compile(r"^[a-z][a-z0-9+.-]*:", re.I)
ATTR_RE = re.compile(r"""((?:href|src)\s*=\s*)(["'])((?:(?!\2).)*)\2""", re.S)
CARDS_LINK_RE = re.compile(r"^cards/([a-z0-9][a-z0-9\-]{0,79})\.html$")
SHELL_LINK_RE = re.compile(r"^tool\.html\?(?:card|t)=([a-z0-9][a-z0-9\-]{0,79})(?:$|&)")


def rewrite_asset(value: str) -> str:
    """A card is written for a root-level host (index.html / tool.html), so a
    bare relative link in its markup means 'from the site root'. From tool/ it
    would 404 one directory down — make it root-absolute. Values that already
    address themselves (scheme, protocol-relative, anchor, absolute) are
    left exactly as written."""
    v = value.strip()
    if not v or v.startswith(("#", "/", "//")) or SCHEME_RE.match(v):
        return value
    cards = CARDS_LINK_RE.match(v)
    if cards:
        return "/tool/" + cards.group(1) + ".html"
    shell = SHELL_LINK_RE.match(v)
    if shell:
        return "/tool/" + shell.group(1) + ".html"
    if " " in v:
        return value  # not a plain link; never guess
    return "/" + value


def split_scripts(fragment: str) -> list[tuple[str, bool]]:
    """(chunk, is_script) pieces: <script>…</script> (any attributes, incl.
    src) stays byte-for-byte untouched; only the markup between them is
    rewritten."""
    out: list[tuple[str, bool]] = []
    pos = 0
    for m in re.finditer(r"<script\b[^>]*>.*?</script>", fragment, re.S | re.I):
        if m.start() > pos:
            out.append((fragment[pos:m.start()], False))
        out.append((m.group(0), True))
        pos = m.end()
    if pos < len(fragment):
        out.append((fragment[pos:], False))
    return out or [("", False)]


def inline_fragment(fragment: str) -> str:
    return "".join(
        chunk if is_script else ATTR_RE.sub(
            lambda m: m.group(1) + m.group(2) + rewrite_asset(m.group(3)) + m.group(2),
            chunk,
        )
        for chunk, is_script in split_scripts(fragment)
    )

# --------------------------------------------------------------------------
# Page chrome
# --------------------------------------------------------------------------
THEMES_BOOTSTRAP = """<script>
/* The palette a visitor picked on the home page follows them onto every
   tool page, as it does on tool.html: accent, then background theme. Runs
   before first paint; a missing or tampered store falls back to the site's
   default colours. */
(function () {
  try {
    var accent = localStorage.getItem('accent');
    if (/^#[0-9a-fA-F]{6}$/.test(accent || '')) {
      document.documentElement.style.setProperty('--accent', accent);
    }
    var THEMES = {
      'default': ['#0a0f14', '#141e28'],
      'deep-blue': ['#05080c', '#0f151f'],
      'deep-purple': ['#12081a', '#1f1229'],
      'deep-teal': ['#061616', '#0f2525'],
      'deep-red': ['#160606', '#251010'],
      'deep-forest': ['#081408', '#152015'],
      'deep-space': ['#000814', '#1a1a2e']
    };
    var theme = THEMES[localStorage.getItem('theme')];
    if (theme) {
      document.documentElement.style.setProperty('--mp-bg1', theme[0]);
      document.documentElement.style.setProperty('--mp-bg2', theme[1]);
    }
  } catch (e) { /* defaults win */ }
})();
</script>"""

# No <link rel="preload"> for the font (same reasoning as index.html): the
# @font-face below is inline in this head, so the download starts at parse
# time anyway, and the preload costs the "preloaded … was not used within a
# few seconds" console warning on every cached repeat visit.
FONTS = """<style>
/* Inter, self-hosted (fonts/, SIL OFL 1.1) — the same faces as tool.html. */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-display: swap;
  font-weight: 100 900;
  src: url(../fonts/inter-latin-ext.woff2) format('woff2-variations');
  unicode-range: U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF;
}
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-display: swap;
  font-weight: 100 900;
  src: url(../fonts/inter-latin.woff2) format('woff2-variations');
  unicode-range: U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6-02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD;
}
</style>"""

CHROME_CSS = """
/* tp- chrome: the page is one tool, full-size. The card styles itself; this
   is only the frame — nav, search, crumbs, previous/next, related, footer. */
:root{--tp-accent:#2dd4ff;--tp-gold:#ffd700;--tp-text:#e6faff;--tp-muted:rgba(230,250,255,.62);--tp-line:rgba(255,255,255,.09);--tp-surface:#141e28}
*{box-sizing:border-box}
html{color-scheme:dark;-webkit-text-size-adjust:100%;scroll-behavior:smooth}
body{margin:0;background-color:#0a0f14;background:linear-gradient(135deg,var(--mp-bg1,#0a0f14),var(--mp-bg2,#141e28)) fixed;color:var(--tp-text);font-family:'Inter',system-ui,-apple-system,'Segoe UI',sans-serif;line-height:1.6;-webkit-font-smoothing:antialiased;-webkit-tap-highlight-color:transparent;min-height:100vh;min-height:100dvh;display:flex;flex-direction:column}
::selection{background:rgba(45,212,255,.3);color:#fff}
:focus-visible{outline:2px solid var(--tp-accent);outline-offset:2px;border-radius:4px}
a{color:inherit}
.tp-sr{position:absolute;width:1px;height:1px;margin:-1px;padding:0;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap;border:0}
.tp-skip{position:absolute;top:0;left:0;z-index:2000;padding:10px 16px;font-size:.9rem;font-weight:700;color:#04141c;background:var(--tp-accent);border-radius:0 0 10px 0;text-decoration:none;transform:translateY(-130%);transition:transform .14s ease}
.tp-skip:focus-visible{transform:translateY(0);outline:2px solid #fff;outline-offset:2px}
.tp-nav{position:sticky;top:0;z-index:100;background:rgba(10,15,20,.95);-webkit-backdrop-filter:blur(20px);backdrop-filter:blur(20px);border-bottom:1px solid var(--tp-line)}
.tp-nav-in{max-width:1100px;margin:0 auto;padding:10px 16px;display:flex;align-items:center;gap:12px}
.tp-brand{display:flex;align-items:center;gap:9px;text-decoration:none;font-weight:800;font-size:.9rem;color:var(--tp-text);min-width:0}
.tp-brand:hover{color:var(--tp-accent)}
.tp-mark{display:block;flex:none}
.tp-search{flex:1;min-width:0}
.tp-search input{width:100%;min-height:40px;padding:9px 14px;font:inherit;font-size:.88rem;color:var(--tp-text);background:rgba(255,255,255,.05);border:1px solid var(--tp-line);border-radius:10px;outline:none}
.tp-search input::placeholder{color:var(--tp-muted)}
.tp-search input:focus-visible{outline:2px solid var(--tp-accent);outline-offset:1px}
.tp-nav-acts{display:flex;gap:8px}
.tp-link{display:inline-flex;align-items:center;min-height:40px;padding:8px 12px;border-radius:10px;border:1px solid var(--tp-line);background:rgba(255,255,255,.04);color:var(--tp-text);font-size:.82rem;font-weight:600;text-decoration:none;white-space:nowrap}
.tp-link:hover{border-color:var(--tp-accent);color:var(--tp-accent)}
@media (max-width:760px){
  .tp-nav-in{flex-wrap:wrap;gap:8px;padding:8px 12px}
  .tp-search{order:3;flex-basis:100%}
  .tp-brand span{font-size:.8rem}
  .tp-link{min-height:36px;padding:6px 10px;font-size:.78rem}
}
.tp-main{flex:1;width:100%;max-width:960px;margin:0 auto;padding:24px 16px 40px;scroll-margin-top:84px}
.tp-crumbs{display:flex;flex-wrap:wrap;gap:6px;align-items:center;font-size:.8rem;color:var(--tp-muted);margin-bottom:18px}
.tp-crumbs a{color:var(--tp-muted);text-decoration:none}
.tp-crumbs a:hover{color:var(--tp-accent)}
.tp-crumbs [aria-current="page"]{color:var(--tp-text);font-weight:600}
.tp-sep{opacity:.5}
.tp-tool{background:var(--tp-surface);border:1px solid var(--tp-line);border-radius:14px;padding:28px;box-shadow:0 16px 40px rgba(0,0,0,.4);margin-bottom:28px;min-width:0}
.tp-tool>*{min-width:0;max-width:100%}
.tp-pn{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:0 0 32px}
@media (max-width:600px){.tp-pn{grid-template-columns:1fr}}
.tp-pn-a{display:flex;flex-direction:column;gap:3px;padding:12px 14px;background:rgba(255,255,255,.03);border:1px solid var(--tp-line);border-radius:12px;text-decoration:none;min-width:0;transition:border-color .15s,transform .15s,background .15s}
.tp-pn-a:hover{border-color:var(--tp-accent);background:rgba(45,212,255,.05);transform:translateY(-1px);text-decoration:none}
.tp-pn-a.tp-pn-r{text-align:right;align-items:flex-end}
.tp-pn-k{font-size:.72rem;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:var(--tp-accent)}
.tp-pn-t{font-size:.9rem;font-weight:600;color:var(--tp-text);line-height:1.3;overflow:hidden;text-overflow:ellipsis;display:-webkit-box;-webkit-line-clamp:1;-webkit-box-orient:vertical}
.tp-rel{border-top:1px solid var(--tp-line);padding-top:24px}
.tp-rel h2{font-size:1.05rem;font-weight:800;color:#fff;margin:0 0 12px}
.tp-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:10px}
.tp-gwrap{display:flex;min-width:0}
.tp-g{flex:1;display:flex;flex-direction:column;gap:4px;min-width:0;padding:12px 14px;background:rgba(255,255,255,.03);border:1px solid var(--tp-line);border-radius:10px;text-decoration:none;transition:border-color .15s,transform .15s,background .15s}
.tp-g:hover{border-color:var(--tp-accent);background:rgba(45,212,255,.05);transform:translateY(-1px);text-decoration:none}
.tp-g .xp-title{font-size:.85rem;font-weight:700;color:var(--tp-text);line-height:1.3}
.tp-gd{font-size:.74rem;color:var(--tp-muted);line-height:1.4;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}
.tp-gwrap .xp-actions{margin-left:6px;align-self:center}
.tp-more{margin:14px 0 0;font-size:.88rem}
.tp-more a{color:var(--tp-accent);text-decoration:none;font-weight:600}
.tp-more a:hover{text-decoration:underline}
.tp-foot{border-top:1px solid var(--tp-line);margin-top:auto;padding:22px 16px 30px;text-align:center;font-size:.82rem;color:var(--tp-muted)}
.tp-foot-links{margin:0 0 8px;line-height:2.1}
.tp-foot-links a{color:var(--tp-text);text-decoration:none;margin:0 6px}
.tp-foot-links a:hover{color:var(--tp-accent)}
.tp-foot-note{margin:0;font-size:.78rem}
@media (prefers-reduced-motion:reduce){*{transition:none!important;scroll-behavior:auto!important}}
"""

FOOT_LINKS = (
    '<a href="../index.html">All __COUNT__ tools</a> · '
    '<a href="../about.html">About</a> · '
    '<a href="../press.html">Press</a> · '
    '<a href="../tools-index.html">Index</a> · '
    '<a href="../popular.html">Popular</a> · '
    '<a href="../new.html">New</a> · '
    '<a href="../use-case.html">Use case</a> · '
    '<a href="../help.html">Help</a> · '
    '<a href="../changelog.html">Changelog</a> · '
    '<a href="../embed.html">Embed</a> · '
    '<a href="../sitemap.html">Sitemap</a> · '
    '<a href="../blog/">Blog</a> · '
    '<a href="../donate.html">Donate</a> · '
    '<a href="../sponsor.html">Sponsor</a>'
)


def boot_script(slug: str, title: str, category: str) -> str:
    # Plain string + placeholder substitution: the JavaScript below is full
    # of braces, and an f-string turns every one into a footgun.
    js = """<script>
/* tp- boot: everything the card itself cannot know about. The card is the
   page's main content and runs from its own inline scripts; this adds the
   site's duty-of-care notice, the "Continue:" history, the six cards'
   legacy support link, and the search shortcut. None of it may block or
   replace the tool. */
(function () {
  'use strict';
  var SLUG = __SLUG__;
  var TITLE = __TITLE__;
  var CATEGORY = __CATEGORY__;
  function ready(fn) {
    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', fn);
    else fn();
  }
  ready(function () {
    /* YMYL duty-of-care notice for health/finance tools — the same call
       tool.html makes once its fragment is mounted. */
    try {
      if (window.SiteRiskNotices) {
        window.SiteRiskNotices.attach(document.getElementById('tool-root'), { name: SLUG, category: CATEGORY });
      }
    } catch (e) {}
    /* The home page's "Continue:" chips read this list; same shape as
       tool.html's rememberRecent() so a visit here continues the trail. */
    try {
      var rec = JSON.parse(localStorage.getItem('__mp_recent') || '[]');
      if (!Array.isArray(rec)) rec = [];
      rec = rec.filter(function (x) { return x && x.slug !== SLUG; });
      rec.unshift({ slug: SLUG, title: TITLE.slice(0, 80) });
      localStorage.setItem('__mp_recent', JSON.stringify(rec.slice(0, 8)));
    } catch (e) {}
  });
  /* Six older cards end with a "support this site" link written as
     onclick="showContributionsPanel()". The function lived on index.html's
     old app and is re-declared by tool.html for that reason; the full page
     answers the same call, or the click would throw. */
  window.showContributionsPanel = function () {
    location.href = '../index.html#contributionsPanel';
  };
  /* '/' goes to the catalogue search, as on the list pages. */
  document.addEventListener('keydown', function (e) {
    if (e.ctrlKey || e.metaKey || e.altKey) return;
    var t = e.target;
    if (t && (t.tagName === 'INPUT' || t.tagName === 'TEXTAREA' || t.tagName === 'SELECT' || t.isContentEditable)) return;
    if (e.key === '/') { e.preventDefault(); location.href = '../index.html'; }
  });
})();
</script>"""
    return (js.replace("__SLUG__", json.dumps(slug))
              .replace("__TITLE__", json.dumps(title))
              .replace("__CATEGORY__", json.dumps(category)))


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------
def ld(obj) -> str:
    return json.dumps(obj, ensure_ascii=False, separators=(", ", ": "))


def render_page(tool: dict, fragment: str, ctx: dict) -> str:
    slug = tool["name"]
    title = tool["title"]
    desc = truncate(tool.get("description") or "Free browser tool.", 155)
    cat = tool.get("category") or "General Tool"
    cat_slug = slugify_category(cat)
    cat_count = ctx["cat_count"].get(cat, 0)
    canonical = f"{SITE}/tool/{slug}.html"
    v = ctx["version"]

    prev = ctx["prev_next"].get(slug, (None, None))[0]
    nxt = ctx["prev_next"].get(slug, (None, None))[1]
    related = ctx["related"].get(slug, [])

    webapp = {
        "@context": "https://schema.org",
        "@type": "WebApplication",
        "name": title,
        "url": canonical,
        "description": truncate(tool.get("description") or "", 300),
        "applicationCategory": "UtilitiesApplication",
        "operatingSystem": "Any (web browser)",
        "offers": {"@type": "Offer", "price": "0", "priceCurrency": "GBP"},
        "isPartOf": {"@type": "WebSite", "name": "The Most Useful Site in The World", "url": SITE + "/"},
    }
    crumbs = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": SITE + "/"},
            {"@type": "ListItem", "position": 2, "name": "Tools", "item": f"{SITE}/tools-index.html"},
            {"@type": "ListItem", "position": 3, "name": cat, "item": f"{SITE}/categories/{cat_slug}.html"},
            {"@type": "ListItem", "position": 4, "name": title, "item": canonical},
        ],
    }

    def pn(href: str | None, label: str, t: dict | None, flip: bool) -> str:
        if not href or not t:
            return ""
        cls = "tp-pn-a tp-pn-r" if flip else "tp-pn-a"
        return (f'<a class="{cls}" href="{esc(href)}">'
                f'<span class="tp-pn-k">{esc(label)}</span>'
                f'<span class="tp-pn-t">{esc(t["title"])}</span></a>')

    pn_prev = pn((prev + ".html") if prev else None, f"← Previous in {cat}", ctx["by_name"].get(prev), False)
    pn_next = pn((nxt + ".html") if nxt else None, f"Next in {cat} →", ctx["by_name"].get(nxt), True)

    grid = ""
    for r in related:
        rt = ctx["by_name"].get(r)
        if not rt:
            continue
        grid += (
            f'<div class="tp-gwrap" data-toolbox-row="{esc(r)}">\n'
            f'  <a class="tp-g" href="{esc(r)}.html">\n'
            f'    <span class="xp-title">{esc(rt["title"])}</span>\n'
            f'    <span class="tp-gd">{esc(truncate(rt.get("description") or "", 120))}</span>\n'
            f'  </a>\n'
            f'</div>\n'
        )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover, interactive-widget=resizes-content">
<link rel="icon" href="../favicon.ico" sizes="32x32">
<link rel="icon" href="../favicon.svg" type="image/svg+xml">
<title>{esc(title)} · The Most Useful Site in The World</title>
<meta name="description" content="{esc(desc)}">
<meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large">
<link rel="canonical" href="{canonical}">
<link rel="alternate" type="application/rss+xml" title="The Most Useful Site in The World — RSS feed" href="../feed.xml">
<meta name="theme-color" content="#0a0f14">
<meta property="og:type" content="website">
<meta property="og:site_name" content="The Most Useful Site in The World">
<meta property="og:title" content="{esc(title)} — free, no sign-up">
<meta property="og:description" content="{esc(desc)}">
<meta property="og:url" content="{canonical}">
<meta property="og:image" content="{SITE}/og-tools.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{esc(title)} — free, no sign-up">
<meta name="twitter:description" content="{esc(desc)}">
<meta name="twitter:image" content="{SITE}/og-tools.png">
<script type="application/ld+json">{ld(webapp)}</script>
<script type="application/ld+json">{ld(crumbs)}</script>
{FONTS}
{THEMES_BOOTSTRAP}
<link rel="stylesheet" href="../cards/card.css">
<link rel="stylesheet" href="../toolbox.css?v={v}">
<style>
{CHROME_CSS.strip()}
</style>
</head>
<body>
{MARKER}
<a class="tp-skip" href="#tool-root">Skip to the tool</a>
<nav class="tp-nav" aria-label="Site">
  <div class="tp-nav-in">
    <a class="tp-brand" href="../index.html"><img class="tp-mark" src="../logo-mark.svg" alt="" width="22" height="22"><span>The Most Useful Site in The World</span></a>
    <form class="tp-search" role="search" action="../index.html" method="get">
      <label class="tp-sr" for="tp-q">Search all {ctx['count']} tools</label>
      <input id="tp-q" type="search" name="q" placeholder="Search {ctx['count']} tools" autocomplete="off">
    </form>
    <div class="tp-nav-acts">
      <a class="tp-link" href="../tools-index.html">📚 All tools</a>
      <a class="tp-link" href="../categories/{esc(cat_slug)}.html">{esc(cat)}</a>
    </div>
  </div>
</nav>
<main id="tool-main" class="tp-main">
  <nav class="tp-crumbs" aria-label="Breadcrumb">
    <a href="../index.html">Home</a><span class="tp-sep" aria-hidden="true">›</span>
    <a href="../tools-index.html">Tools</a><span class="tp-sep" aria-hidden="true">›</span>
    <a href="../categories/{esc(cat_slug)}.html">{esc(cat)}</a><span class="tp-sep" aria-hidden="true">›</span>
    <span aria-current="page">{esc(title)}</span>
  </nav>
  <h1 class="tp-sr">{esc(title)}</h1>
  <div class="card tp-tool" id="tool-root">
{inline_fragment(fragment)}
  </div>
  <nav class="tp-pn" aria-label="More tools in {esc(cat)}">
    {pn_prev}
    {pn_next}
  </nav>
  <section class="tp-rel" aria-labelledby="tp-rel-h">
    <h2 id="tp-rel-h">More in {esc(cat)}</h2>
    <div class="tp-grid">
{grid}    </div>
    <p class="tp-more"><a href="../categories/{esc(cat_slug)}.html">All {cat_count} tools in {esc(cat)} →</a></p>
  </section>
</main>
<footer class="tp-foot">
  <p class="tp-foot-links">{FOOT_LINKS.replace('__COUNT__', str(ctx['count']))}</p>
  <p class="tp-foot-note">No ads · no accounts · no sign-ups · no paywalls · this tool runs entirely in your browser</p>
</footer>
<script defer src="../risk-notices.js?v={v}"></script>
<script defer src="../toolbox.js?v={v}"></script>
{boot_script(slug, title, cat)}
</body>
</html>
"""

# --------------------------------------------------------------------------
# Context: ordering, previous/next, related
# --------------------------------------------------------------------------
def load_context(tools: list[dict]) -> dict:
    by_name = {t["name"]: t for t in tools}
    cat_tools: dict[str, list[dict]] = {}
    for t in tools:
        cat_tools.setdefault(t.get("category") or "General Tool", []).append(t)
    for cat in cat_tools:
        cat_tools[cat].sort(key=lambda t: (title_sort_key(t["title"]), t["name"]))

    prev_next: dict[str, tuple[str | None, str | None]] = {}
    for cat, group in cat_tools.items():
        n = len(group)
        for i, t in enumerate(group):
            if n == 1:
                prev_next[t["name"]] = (None, None)  # nothing to move to
            else:
                prev_next[t["name"]] = (group[i - 1]["name"], group[(i + 1) % n]["name"])

    try:
        with open(RELATED_JSON, encoding="utf-8") as fh:
            related_raw = json.load(fh)
    except (OSError, json.JSONDecodeError):
        related_raw = {}

    related: dict[str, list[str]] = {}
    for t in tools:
        slug = t["name"]
        cat = t.get("category") or "General Tool"
        ranked = related_raw.get(slug) or []
        picked = [s for s in ranked if s in by_name and s != slug][:8]
        if len(picked) < 8:
            skip = set(picked) | {slug, *prev_next.get(slug, (None, None))}
            for candidate in cat_tools.get(cat, []):
                if len(picked) >= 8:
                    break
                c = candidate["name"]
                if c in skip or c in picked:
                    continue
                picked.append(c)
        related[slug] = picked

    return {
        "count": len(tools),
        "version": asset_version(),
        "by_name": by_name,
        "cat_count": {c: len(g) for c, g in cat_tools.items()},
        "prev_next": prev_next,
        "related": related,
    }

# --------------------------------------------------------------------------
# Build / check
# --------------------------------------------------------------------------
def load_inputs() -> list[dict]:
    with open(CARDS_JSON, encoding="utf-8") as fh:
        tools = json.load(fh)
    if not isinstance(tools, list) or not tools:
        raise SystemExit("cards/cards.json is missing or empty — run: node generate-cards-json.js")
    return tools


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="fail when a rendered page differs from disk, a page is missing, or tool/ holds a page no tool declares")
    args = parser.parse_args()

    tools = load_inputs()
    ctx = load_context(tools)
    os.makedirs(OUT_DIR, exist_ok=True)

    drifted, written, missing = [], 0, []
    for tool in sorted(tools, key=lambda t: t["name"]):
        slug = tool["name"]
        frag_path = os.path.join(CARDS_DIR, slug + ".html")
        if not os.path.exists(frag_path):
            missing.append(slug)
            continue
        with open(frag_path, encoding="utf-8") as fh:
            fragment = fh.read()
        out = render_page(tool, fragment, ctx)
        target = os.path.join(OUT_DIR, slug + ".html")
        if args.check:
            if not os.path.exists(target):
                missing.append(slug)
            elif open(target, encoding="utf-8").read() != out:
                drifted.append(f"tool/{slug}.html")
        else:
            with open(target, "w", encoding="utf-8") as fh:
                fh.write(out)
            written += 1

    on_disk = {f[:-5] for f in os.listdir(OUT_DIR) if f.endswith(".html")}
    declared = {t["name"] for t in tools}
    orphans = sorted(on_disk - declared)

    if missing:
        print(f"  FAIL {len(missing)} tool page(s) missing a card fragment: {', '.join(missing[:8])}", file=sys.stderr)
        return 1
    if orphans:
        print(f"  FAIL tool/ page(s) with no tool in cards.json: {', '.join(orphans[:8])}", file=sys.stderr)
        print("       every file in tool/ is generated — delete orphans, they are not homes", file=sys.stderr)
        return 1
    if args.check:
        if drifted:
            print("tool/ full pages are stale — run: python3 scripts/build-tool-fullpages.py", file=sys.stderr)
            for path in drifted[:20]:
                print(f"  drift {path}", file=sys.stderr)
            return 1
        print(f"tool full pages OK — {len(tools)} page(s) match the cards")
        return 0

    total_kb = sum(os.path.getsize(os.path.join(OUT_DIR, t["name"] + ".html")) for t in tools)
    print(f"tool full pages: {written} written ({len(tools)} tools, {total_kb / 1048576:.1f} MB total) at tool/<slug>.html")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
