#!/usr/bin/env python3
"""discovery_catalogue.py — one reader for "what tools exist, in what order".

Shared by the discovery-surface generators (build-tools-page.py,
build-html-sitemap.py, build-related.py) and by check-tool-graph.py, so every
static page that lists tools agrees on the catalogue, the category order and
the ordering inside a category. A surface that sorts its own way is a surface
that drifts its own way.

The source of truth is unchanged and stays unchanged:

  * cards/cards.json  — generated by generate-cards-json.js from the cards/
                        folder (the folder is the truth; see AGENTS.md §4).
  * tools-index.json  — generated by scripts/build-tools-index.js; it owns the
                        canonical CATEGORY ORDER and the per-category icon.

Nothing here writes anything. Zero third-party dependencies.
"""
from __future__ import annotations

import json
import os
import re
import unicodedata
from dataclasses import dataclass, field

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CARDS_JSON = os.path.join(ROOT, "cards", "cards.json")
CARDS_LITE_JSON = os.path.join(ROOT, "cards", "cards-lite.json")
CARDS_DIR = os.path.join(ROOT, "cards")
TOOLS_INDEX_JSON = os.path.join(ROOT, "tools-index.json")


def slugify_category(name: str) -> str:
    """The category slug used by categories/<slug>.html and every #cat- anchor.

    Byte-for-byte the rule in scripts/build-tools-index.js (`slugCat`) and the
    one tool.html re-implements at runtime for its "Explore Category" tile, so
    a generator that got this wrong would emit anchors that 404.
    """
    s = name.lower().replace("&", "and")
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


# Leading emoji / punctuation / whitespace never take part in A–Z ordering:
# "🌀 3D Spirograph Nebula" sorts under "3", not under the emoji codepoint.
_TITLE_NOISE = re.compile(
    r"^[\s\W_]+", re.UNICODE
)


def title_sort_key(title: str) -> str:
    """Case-folded, emoji-stripped, accent-folded sort key for a tool title."""
    stripped = _TITLE_NOISE.sub("", title or "")
    if not stripped:  # a title that is *only* symbols sorts on the raw text
        stripped = title or ""
    folded = unicodedata.normalize("NFKD", stripped)
    folded = "".join(ch for ch in folded if not unicodedata.combining(ch))
    return folded.casefold()


@dataclass(frozen=True)
class Tool:
    name: str
    title: str
    description: str
    category: str
    path: str

    @property
    def url(self) -> str:
        """The standalone-tool URL every static surface must link to."""
        return f"tool.html?card={self.name}"


@dataclass(frozen=True)
class Category:
    name: str
    slug: str
    icon: str
    tools: tuple = field(default_factory=tuple)


class Catalogue:
    """The catalogue plus its canonical category order."""

    def __init__(self, tools: list[Tool], categories: list[Category]) -> None:
        self.tools = tools
        self.categories = categories
        self.by_name = {t.name: t for t in tools}
        self.by_slug = {c.slug: c for c in categories}

    def __len__(self) -> int:
        return len(self.tools)

    @property
    def names(self) -> set[str]:
        return set(self.by_name)

    def sorted_tools(self, tools) -> list[Tool]:
        """A–Z by title, slug as the deterministic tie-break."""
        return sorted(tools, key=lambda t: (title_sort_key(t.title), t.name))


def _load_json(path: str):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def load_catalogue() -> Catalogue:
    """Read cards/cards.json and order it with tools-index.json's categories."""
    raw = _load_json(CARDS_JSON)
    tools = [
        Tool(
            name=str(item["name"]),
            title=str(item.get("title") or item["name"]),
            description=str(item.get("description") or ""),
            category=str(item.get("category") or ""),
            path=str(item.get("path") or f"cards/{item['name']}.html"),
        )
        for item in raw
    ]

    grouped: dict[str, list[Tool]] = {}
    for tool in tools:
        grouped.setdefault(tool.category, []).append(tool)

    order: list[tuple[str, str]] = []
    if os.path.exists(TOOLS_INDEX_JSON):
        index = _load_json(TOOLS_INDEX_JSON)
        for cat in index.get("categories", []):
            order.append((str(cat.get("name", "")), str(cat.get("icon", ""))))

    known = {name for name, _ in order}
    # A category the catalogue grew after tools-index.json was last built must
    # still get a section (sorted after the canonical ones) rather than being
    # silently dropped from every static surface.
    for name in sorted(grouped):
        if name not in known:
            order.append((name, ""))

    categories = [
        Category(
            name=name,
            slug=slugify_category(name),
            icon=icon,
            tools=tuple(
                sorted(grouped[name], key=lambda t: (title_sort_key(t.title), t.name))
            ),
        )
        # An empty category is not a section: it would render a heading with a
        # count of zero on every static surface. check-tool-graph.py is what
        # notices a category that lost all its tools.
        for name, icon in order
        if grouped.get(name)
    ]
    return Catalogue(tools, categories)


def card_files_on_disk() -> set[str]:
    """Every slug with a fragment in cards/ (the folder is the truth)."""
    return {
        fn[:-5]
        for fn in os.listdir(CARDS_DIR)
        if fn.endswith(".html")
    }


def load_lite_tier() -> list[dict]:
    if not os.path.exists(CARDS_LITE_JSON):
        return []
    return _load_json(CARDS_LITE_JSON)
