#!/usr/bin/env bash
# rollback.sh — guided production recovery for a static GitHub Pages site.
#
# Why a script: during an incident the useful thing is not cleverness, it is a
# short sequence that cannot make things worse. This one refuses to run on a
# dirty tree, never pushes to the default branch, never force-pushes, and proves
# the revert with `scripts/verify.sh` before it offers a pull request.
#
# Default behaviour is --plan-only: it prints exactly what it would do and
# changes nothing. Add --execute when you mean it.
#
# Usage:
#   bash scripts/rollback.sh                       # plan for reverting HEAD
#   bash scripts/rollback.sh --ref <sha>           # plan for reverting a commit
#   bash scripts/rollback.sh --ref <sha> --execute # do it, verify, open a PR
#   bash scripts/rollback.sh --execute --reason "why this revert is happening"
#
# See docs/OPERATIONS.md §6 for when to revert and when to fix forward.
set -euo pipefail

cd "$(dirname "$0")/.." || exit 1
ROOT=$(pwd)

REF="HEAD"
EXECUTE=0
REASON=""
BRANCH=""

die() { printf '\033[31mrollback: %s\033[0m\n' "$1" >&2; exit 1; }
say() { printf '%s\n' "$1"; }
step() { printf '\n\033[1m== %s\033[0m\n' "$1"; }

while [ "$#" -gt 0 ]; do
  case "$1" in
    --ref) REF="${2:-}"; shift 2 ;;
    --execute) EXECUTE=1; shift ;;
    --plan-only) EXECUTE=0; shift ;;
    --reason) REASON="${2:-}"; shift 2 ;;
    --branch) BRANCH="${2:-}"; shift 2 ;;
    -h|--help)
      sed -n '2,25p' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) die "unknown argument $1" ;;
  esac
done

[ -n "$REF" ] || die "--ref needs a commit"

command -v git >/dev/null 2>&1 || die "git is required"

step "Rollback plan"
SUBJECT=$(git log -1 --format='%h %s' "$REF" 2>/dev/null) || die "cannot resolve $REF in this repository"
SHA=$(git rev-parse "$REF")
say "  Commit to revert : $SUBJECT"
say "  Full sha         : $SHA"
say "  Branch to create : ${BRANCH:-ops/rollback-<short-sha>}"
say "  Mode             : $([ "$EXECUTE" = 1 ] && echo 'execute' || echo 'plan only (nothing will change)')"
[ -n "$REASON" ] && say "  Reason           : $REASON"

say ""
say "The script would:"
say "  1. refuse to continue unless the working tree is clean"
say "  2. fetch origin/main and branch from it"
say "  3. git revert --no-edit $SHA"
say "  4. run 'bash scripts/verify.sh' on the result and stop if it fails"
say "  5. push the branch and open a pull request against main (never a direct push)"

if [ "$EXECUTE" != 1 ]; then
  step "Plan only — nothing was changed"
  say "Re-run with --execute to carry it out. If the site is down and you have write"
  say "access, the owner's fast path in docs/OPERATIONS.md §6 is a direct revert on main:"
  say "  git switch main && git pull --ff-only"
  say "  git revert --no-edit $SHA && git push origin main"
  exit 0
fi

step "Preflight"
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
  die "working tree is not clean — commit or stash first, so a rollback commit contains only the revert"
fi
say "  working tree clean"

git fetch origin main --quiet || die "cannot fetch origin/main"
BASE_SHA=$(git rev-parse FETCH_HEAD)
say "  origin/main at $(git rev-parse --short "$BASE_SHA")"

if ! git merge-base --is-ancestor "$SHA" "$BASE_SHA"; then
  say "  note: $SHA is not an ancestor of origin/main (still permitted — check the plan above)"
fi

BRANCH=${BRANCH:-"ops/rollback-$(git rev-parse --short "$SHA")-$(date -u +%Y%m%d%H%M)"}
git show-ref --verify --quiet "refs/heads/$BRANCH" && die "branch $BRANCH already exists"

step "Create the revert"
git switch --create "$BRANCH" "$BASE_SHA" --quiet || die "cannot create $BRANCH"
if ! git revert --no-edit "$SHA"; then
  git revert --abort 2>/dev/null || true
  die "the revert conflicts (usually a generated artefact). Fix forward instead, or revert the pair of commits — see docs/OPERATIONS.md §6"
fi
say "  reverted $(git rev-parse --short "$SHA") on $BRANCH"

step "Prove the revert with verify.sh"
if ! bash scripts/verify.sh; then
  say ""
  die "verify.sh failed on the revert. The revert is committed on $BRANCH and has NOT been pushed.
Inspect it, fix it, or discard the branch:
  git switch main && git branch -D $BRANCH"
fi

step "Push and open one pull request"
git push --set-upstream origin "$BRANCH"
BODY=$(mktemp)
{
  printf 'Rollback of `%s`.\n\n' "$SHA"
  printf '**Reverted commit:** %s\n\n' "$SUBJECT"
  [ -n "$REASON" ] && printf '**Reason:** %s\n\n' "$REASON"
  printf 'Generated by `scripts/rollback.sh`. `scripts/verify.sh` passed on this branch before it was pushed.\n\n'
  printf 'Runbook: [docs/OPERATIONS.md](https://github.com/%s/blob/main/docs/OPERATIONS.md) §6–§7.\n\n' \
    "$(git remote get-url origin | sed -E 's#.*github\.com[:/]([^/]+/[^/.]+)(\.git)?$#\1#')"
  printf 'Merge this, then confirm recovery with the production monitor (its post-deploy run checks the\n'
  printf 'deployed commit automatically, and the next full run closes the `ops:production-alert` issue).\n'
} > "$BODY"

if command -v gh >/dev/null 2>&1; then
  gh pr create --base main --head "$BRANCH" \
    --title "Rollback: revert $(git rev-parse --short "$SHA")" \
    --body-file "$BODY" || say "  (gh could not open the PR automatically — the branch is pushed, open it by hand)"
else
  say "  gh is not installed — the branch is pushed; open the pull request by hand"
fi
rm -f "$BODY"

step "Next"
say "  1. Review and merge the pull request (never push to main directly unless the site is down)."
say "  2. Wait for the post-deploy production monitor run, then the next full run."
say "  3. Close nothing by hand: the monitor closes the alert issue when the contract holds again."
say "  4. See docs/OPERATIONS.md §8 — every incident should leave a gate behind."
